/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim\lib -o C:\projects\easygl\examples\nimcache\easygl_textures.o C:\projects\easygl\examples\nimcache\easygl_textures.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_4Xyxy0Om14N6K1l5e9bUPSQ tySequence_4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_9bAGqSvkAaFL9bWjsEPslrFA tySequence_9bAGqSvkAaFL9bWjsEPslrFA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ tySequence_6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug;
typedef struct tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
typedef N_CDECL_PTR(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg*, tyProc_A4TgaVzGkRyot8mrE1bD0g) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef NU16 tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw;
typedef NU16 tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA;
typedef NU16 tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw;
typedef NU16 tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA;
typedef NU16 tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw;
typedef NU16 tyEnum_TexImageTarget_4wNONQCfx9aiSc9avZaS5o1w;
typedef NU16 tyEnum_TextureInternalFormat_JO6OJgblQDuq8JEmilKxEw;
typedef NU16 tyEnum_PixelDataFormat_jqJeBox56diuzpllVzXL8Q;
typedef NU16 tyEnum_PixelDataType_cEc9b7cEgtR9b0K320YQVELw;
typedef NU16 tyEnum_MipmapTarget_SUlrCIDio0dfKLufGk9a2tg;
typedef NI32 tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w;
typedef NU8 tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw[52];
struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw padding;
};
typedef NI32 tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg, tyProc_b9aXpKFbsyZ0PIk3aYRVCAA) (tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
typedef NU8 tyEnum_WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw;
struct tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
tyEnum_WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw event;
NU8 pad1;
NU8 pad2;
NU8 pad3;
int data1;
int data2;
};
typedef NU16 tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ;
typedef tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ tyArray_ue9bV4rvhyJDkh6kT7PhDLg[1];
typedef NU16 tyEnum_TextureUnit_Pe1qRsFIu9a5dqer2eHdpAg;
typedef NU8 tyEnum_DrawMode_AmhJunCRQ8PFJ9aloC9ag9bYQ;
typedef NU16 tyEnum_IndexType_KuLW3epA7GK4gjJFmNlYtw;
typedef N_CDECL_PTR(void, tyProc_T629bWTbvDFNyKAaO0BGGIQ) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w {
char dummy;
};
struct tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg {
char dummy;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_4Xyxy0Om14N6K1l5e9bUPSQ {
  TGenericSeq Sup;
  NF32 data[SEQ_DECL_SIZE];
};
struct tySequence_9bAGqSvkAaFL9bWjsEPslrFA {
  TGenericSeq Sup;
  NU32 data[SEQ_DECL_SIZE];
};
struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimLoadProcs0)(void);
N_NIMCALL(NU32, CreateAndLinkProgram_vn5ROZF0pfhPx6U9bF9ccGXw)(NimStringDesc* vertexPath, NimStringDesc* fragmentPath, NimStringDesc* geometryPath);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_INbm9aJ9a9blRlORom2TaXUtg_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_NIMCALL(void, TM_INbm9aJ9a9blRlORom2TaXUtg_7)(void);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
static N_INLINE(NU32, GenVertexArray_y9aWBmx772xkm1fCOo2NcFAeasygl)(void);
N_STDCALL(void, glGenVertexArrays_zvqeRPLD9c2eggqLYZ1r3Zg)(NI32 n, NU32* arrays);
static N_INLINE(NU32, GenBuffer_xxU7oJIkwZkPfbkUj9aKWpgeasygl)(void);
N_STDCALL(void, glGenBuffers_B9ax9aWnWORHtXpch5OZqE6g)(NI32 n, NU32* buffers);
static N_INLINE(void, BindVertexArray_1olxbPfcB1SGdKsshWP3wgeasygl)(NU32 vertexArray);
N_STDCALL(void, glBindVertexArray_DTfQaj6wT6HQ9c375GwSXmg)(NU32 array);
static N_INLINE(void, BindBuffer_W9bN003jC8Uhvy4z5xdUL9bAeasygl)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NU32 buffer);
N_STDCALL(void, glBindBuffer_3rtrqe5eYHMVBLzlqTY63w)(NU32 target, NU32 buffer);
static N_INLINE(void, BufferData_9c9bFitUJKUzqcspXMNZg4Iwtextures)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NF32* data, NI dataLen_0, tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA usage);
N_STDCALL(void, glBufferData_00Qu57bAXtAMX49bzkHe6aQ)(NU32 target, NI size, void* data, NU32 usage);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, BufferData_NHhcuX9a476t2DF9ccAE29csQtextures)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NU32* data, NI dataLen_0, tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA usage);
static N_INLINE(void, VertexAttribPointer_rpmL9b1Xbhw9au2jacf9chz2geasygl)(NU32 index, NI size, tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw attribType, NIM_BOOL normalized, NI32 stride, NI32 pointer);
N_STDCALL(void, glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer);
static N_INLINE(void, EnableVertexAttribArray_xe9ai9b74zILHV5CMYQeQAVgeasygl)(NU32 indeX);
N_STDCALL(void, glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA)(NU32 index);
N_NIMCALL(NU32, GenTexture_KDNM0klSr3qVvz89a9b0xoCw)(void);
N_NIMCALL(void, BindTexture_psAXddCo1UfaZMOxWAy80Q)(tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA target, NU32 texture);
N_NIMCALL(void, TexParameteri_k1oDC9bpuJWK3oPmF9cIROxw)(tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA target, tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw pname, NI32 param);
static N_NIMCALL(void, TM_INbm9aJ9a9blRlORom2TaXUtg_10)(void);
N_NIMCALL(void, setFlipVerticallyOnLoad_ayevlb02tzQDH45TRoMJUg)(NIM_BOOL flip);
N_NIMCALL(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*, load_IpqKxisbLcaIMgU5vJeYeQ)(NimStringDesc* filename, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(NIM_BOOL, eqeq__i5CVqMuqYwWXXhbrePT8aA)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* x, tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* y);
N_NIMCALL(void, TexImage2D_7Lu1IWnN36sTJObNwvi7yQ)(tyEnum_TexImageTarget_4wNONQCfx9aiSc9avZaS5o1w target, NI32 level, tyEnum_TextureInternalFormat_JO6OJgblQDuq8JEmilKxEw internalFormat, NI32 width, NI32 height, tyEnum_PixelDataFormat_jqJeBox56diuzpllVzXL8Q format, tyEnum_PixelDataType_cEc9b7cEgtR9b0K320YQVELw type_0, NU8* data, NI dataLen_0);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, GenerateMipmap_iJouCAx7H7vAFe9cgWStrew)(tyEnum_MipmapTarget_SUlrCIDio0dfKLufGk9a2tg target);
static N_INLINE(void, UseProgram_zLuRnlSabmGQB1f159beDeA_2easygl)(NU32 program);
N_STDCALL(void, glUseProgram_bYudX2ps2dTBClLz2NbyzA_2)(NU32 program);
N_NIMCALL(void, SetInt_TVl5u9c9caFJMWzPp8lSDH1A)(NU32 program, NimStringDesc* name, NI32 value);
N_STDCALL(void, glViewport_yDKviL1Jxz9cvMulIoNt7vQ)(NI32 x, NI32 y, NI32 width, NI32 height);
N_NIMCALL(NIM_BOOL, toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ)(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg some);
N_NIMCALL(void, ClearColor_dPsnFT23vDc9bue9bSM7F6dw)(NF32 r, NF32 g, NF32 b, NF32 a);
static N_INLINE(void, Clear_oYYKmodfLpSojEpZtDQHrgeasygl)(tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ* buffersToClear, NI buffersToClearLen_0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_STDCALL(void, glClear_ecjp09clx9c7t3uIhyfuACGQ)(NU32 mask);
N_NIMCALL(void, ActiveTexture_X1xra1GiiRlEPfa1pegmSA)(tyEnum_TextureUnit_Pe1qRsFIu9a5dqer2eHdpAg texture);
N_NIMCALL(void, DrawElements_t1y9ax9cvJfzgyrfV2IPW85w)(tyEnum_DrawMode_AmhJunCRQ8PFJ9aloC9ag9bYQ mode, NI count, tyEnum_IndexType_KuLW3epA7GK4gjJFmNlYtw indexType, NI offset);
N_NIMCALL(void, DeleteVertexArray_6Mddmv88ZGGy9atNA0qt9cSg)(NU32 vertexArray);
N_NIMCALL(void, DeleteBuffer_PXtHP5umfE4uietYmnGuRw)(NU32 buffer);
static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qtextures)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, opengl_openglInit000)(void);
NIM_EXTERNC N_NOINLINE(void, opengl_openglDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic3dInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic3dDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, easygl_easyglInit000)(void);
NIM_EXTERNC N_NOINLINE(void, easygl_easyglDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stb_image_componentsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stb_image_componentsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stb_image_readInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stb_image_readDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, texturesDatInit000)(void);
extern tyProc_fvOXafK39cW5YZA9b9bzinu9cw Dl_141765_;
int screenWidth_vjbzgzYGWQy5ki2rtZ9cIPg;
int screenHeight_kUdSBZ1Y71t0PBinc225wA;
tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window_7UKPy9bZBX2Sohrm5ymcfCA;
extern tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_142356_;
extern tyProc_A4TgaVzGkRyot8mrE1bD0g Dl_142434_;
NU32 ourShader_pwwci3JDoI3BLHc7foB76A;
tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* vertices_obvszk3Pq7O9cWcVznfC1VQ;
extern TNimType NTI_4Xyxy0Om14N6K1l5e9bUPSQ_;
tySequence_9bAGqSvkAaFL9bWjsEPslrFA* indices_SbLaaOg6YSMYQi383iVLeg;
extern TNimType NTI_9bAGqSvkAaFL9bWjsEPslrFA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NU32 VAO_8RoCMJcu3R7ef4S4GTcnfg;
NU32 VBO_goEXduuaoUdyW5sR7fyiWg;
NU32 EBO_eg09c4OZXlgDHEEdDD0UsRA;
NU32 texture1_vhQZk02gBMTm9bM2Y319cvZQ;
NI width_sXD3CLlh2pfMPS2H9cHfeLg;
NI height_pWysFDIF9cSyeqEdmJajYTQ;
NI channels_Yl9aiUtLUdJKOOzvkEnnJFg;
tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* data_WWEHTX69am8YILp4n9auAmIQ;
extern TNimType NTI_6H5Oh5UUvVCLiakt9aTwtUQ_;
NU32 texture2_YDuKjLLtNRCUFwFbvjoPHw;
tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug evt_pPNt0Sf7d9abHQ9a7GrRW4OA;
extern tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
NIM_BOOL run_JZPBbfeDSYPZ5rtEvJtxPg;
extern tyProc_b9aXpKFbsyZ0PIk3aYRVCAA Dl_142605_;
tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA* windowEvent_jAVoRfSLYjQCCiYeQXCoKw;
int newWidth_lVgBZdubJhDvEGjFqaKzCw;
int newHeight_mC8gViuxlihFtgGSJtVo6Q;
extern tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_142456_;
extern tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_142388_;
STRING_LITERAL(TM_INbm9aJ9a9blRlORom2TaXUtg_2, "shaders/textures.vert", 21);
STRING_LITERAL(TM_INbm9aJ9a9blRlORom2TaXUtg_3, "shaders/textures.frag", 21);
NIM_CONST struct {
  TGenericSeq Sup;
  NF32 data[32];
} TM_INbm9aJ9a9blRlORom2TaXUtg_6 = {{32, 32}, {5.0000000000000000e-001f,
5.0000000000000000e-001f,
0.0f,
1.0000000000000000e+000f,
0.0f,
0.0f,
1.0000000000000000e+000f,
1.0000000000000000e+000f,
5.0000000000000000e-001f,
-5.0000000000000000e-001,
0.0f,
0.0f,
1.0000000000000000e+000f,
0.0f,
1.0000000000000000e+000f,
0.0f,
-5.0000000000000000e-001,
-5.0000000000000000e-001,
0.0f,
0.0f,
0.0f,
1.0000000000000000e+000f,
0.0f,
0.0f,
-5.0000000000000000e-001,
5.0000000000000000e-001f,
0.0f,
1.0000000000000000e+000f,
1.0000000000000000e+000f,
0.0f,
0.0f,
1.0000000000000000e+000f}};
NIM_CONST tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* TM_INbm9aJ9a9blRlORom2TaXUtg_5 = ((tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)&TM_INbm9aJ9a9blRlORom2TaXUtg_6);
STRING_LITERAL(TM_INbm9aJ9a9blRlORom2TaXUtg_11, "textures/container.jpg", 22);
STRING_LITERAL(TM_INbm9aJ9a9blRlORom2TaXUtg_12, "Failure to Load Image", 21);
STRING_LITERAL(TM_INbm9aJ9a9blRlORom2TaXUtg_13, "textures/awesomeface.png", 24);
STRING_LITERAL(TM_INbm9aJ9a9blRlORom2TaXUtg_14, "texture2", 8);
NIM_CONST tyArray_ue9bV4rvhyJDkh6kT7PhDLg TM_INbm9aJ9a9blRlORom2TaXUtg_16 = {((tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ) 16384)}
;
static N_NIMCALL(void, TM_INbm9aJ9a9blRlORom2TaXUtg_4)(void) {
	nimGCvisit((void*)vertices_obvszk3Pq7O9cWcVznfC1VQ, 0);
}
static N_NIMCALL(void, TM_INbm9aJ9a9blRlORom2TaXUtg_7)(void) {
	nimGCvisit((void*)indices_SbLaaOg6YSMYQi383iVLeg, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NU32, GenVertexArray_y9aWBmx772xkm1fCOo2NcFAeasygl)(void) {
	NU32 result;
	nimfr_("GenVertexArray", "easygl.nim");
	result = (NU32)0;
	nimln_(277, "easygl.nim");
	glGenVertexArrays_zvqeRPLD9c2eggqLYZ1r3Zg(((NI32) 1), ((NU32*) ((&result))));
	popFrame();
	return result;
}

static N_INLINE(NU32, GenBuffer_xxU7oJIkwZkPfbkUj9aKWpgeasygl)(void) {
	NU32 result;
	nimfr_("GenBuffer", "easygl.nim");
	result = (NU32)0;
	nimln_(257, "easygl.nim");
	glGenBuffers_B9ax9aWnWORHtXpch5OZqE6g(((NI32) 1), ((NU32*) ((&result))));
	popFrame();
	return result;
}

static N_INLINE(void, BindVertexArray_1olxbPfcB1SGdKsshWP3wgeasygl)(NU32 vertexArray) {
	nimfr_("BindVertexArray", "easygl.nim");
	nimln_(284, "easygl.nim");
	glBindVertexArray_DTfQaj6wT6HQ9c375GwSXmg(vertexArray);
	popFrame();
}

static N_INLINE(void, BindBuffer_W9bN003jC8Uhvy4z5xdUL9bAeasygl)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NU32 buffer) {
	nimfr_("BindBuffer", "easygl.nim");
	nimln_(264, "easygl.nim");
	glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) (target)), buffer);
	popFrame();
}

static N_INLINE(void, BufferData_9c9bFitUJKUzqcspXMNZg4Iwtextures)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NF32* data, NI dataLen_0, tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA usage) {
	NI TM_INbm9aJ9a9blRlORom2TaXUtg_8;
	nimfr_("BufferData", "easygl.nim");
	nimln_(267, "easygl.nim");
	TM_INbm9aJ9a9blRlORom2TaXUtg_8 = mulInt(dataLen_0, ((NI) 4));
	glBufferData_00Qu57bAXtAMX49bzkHe6aQ(((NU32) (target)), (NI)(TM_INbm9aJ9a9blRlORom2TaXUtg_8), ((void*) (data)), ((NU32) (usage)));
	popFrame();
}

static N_INLINE(void, BufferData_NHhcuX9a476t2DF9ccAE29csQtextures)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NU32* data, NI dataLen_0, tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA usage) {
	NI TM_INbm9aJ9a9blRlORom2TaXUtg_9;
	nimfr_("BufferData", "easygl.nim");
	nimln_(267, "easygl.nim");
	TM_INbm9aJ9a9blRlORom2TaXUtg_9 = mulInt(dataLen_0, ((NI) 4));
	glBufferData_00Qu57bAXtAMX49bzkHe6aQ(((NU32) (target)), (NI)(TM_INbm9aJ9a9blRlORom2TaXUtg_9), ((void*) (data)), ((NU32) (usage)));
	popFrame();
}

static N_INLINE(void, VertexAttribPointer_rpmL9b1Xbhw9au2jacf9chz2geasygl)(NU32 index, NI size, tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw attribType, NIM_BOOL normalized, NI32 stride, NI32 pointer) {
	nimfr_("VertexAttribPointer", "easygl.nim");
	nimln_(436, "easygl.nim");
	glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(index, ((NI32) (size)), ((NU32) (attribType)), normalized, stride, ((void*) (pointer)));
	popFrame();
}

static N_INLINE(void, EnableVertexAttribArray_xe9ai9b74zILHV5CMYQeQAVgeasygl)(NU32 indeX) {
	nimfr_("EnableVertexAttribArray", "easygl.nim");
	nimln_(439, "easygl.nim");
	glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(indeX);
	popFrame();
}
static N_NIMCALL(void, TM_INbm9aJ9a9blRlORom2TaXUtg_10)(void) {
	nimGCvisit((void*)data_WWEHTX69am8YILp4n9auAmIQ, 0);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, UseProgram_zLuRnlSabmGQB1f159beDeA_2easygl)(NU32 program) {
	nimfr_("UseProgram", "easygl.nim");
	nimln_(403, "easygl.nim");
	glUseProgram_bYudX2ps2dTBClLz2NbyzA_2(program);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, Clear_oYYKmodfLpSojEpZtDQHrgeasygl)(tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ* buffersToClear, NI buffersToClearLen_0) {
	NU32 mask;
	nimfr_("Clear", "easygl.nim");
	nimln_(451, "easygl.nim");
	if ((NU)(((NI) 0)) >= (NU)(buffersToClearLen_0)) raiseIndexError();
	mask = ((NU32) (buffersToClear[((NI) 0)]));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(452, "easygl.nim");
		colontmp_ = subInt(buffersToClearLen_0, 1);
		nimln_(1973, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1974, "system.nim");
			while (1) {
				NI TM_INbm9aJ9a9blRlORom2TaXUtg_15;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1975, "system.nim");
				i = res;
				nimln_(453, "easygl.nim");
				if ((NU)(i) >= (NU)(buffersToClearLen_0)) raiseIndexError();
				mask = (unsigned int)(mask | ((NU32) (buffersToClear[i])));
				nimln_(1976, "system.nim");
				TM_INbm9aJ9a9blRlORom2TaXUtg_15 = addInt(res, ((NI) 1));
				res = (NI)(TM_INbm9aJ9a9blRlORom2TaXUtg_15);
			} LA3: ;
		}
	}
	nimln_(454, "easygl.nim");
	glClear_ecjp09clx9c7t3uIhyfuACGQ(mask);
	popFrame();
}

static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qtextures)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window) {
	nimfr_("destroy", "sdl2.nim");
	nimln_(1742, "sdl2.nim");
	Dl_142388_(window);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	sdl2_sdl2DatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	opengl_openglDatInit000();
	stdlib_basic2dDatInit000();
	stdlib_basic3dDatInit000();
	easygl_easyglDatInit000();
	stb_image_componentsDatInit000();
	stb_image_readDatInit000();
	texturesDatInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	sdl2_sdl2Init000();
	stdlib_sequtilsInit000();
	stdlib_dynlibInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	opengl_openglInit000();
	stdlib_basic2dInit000();
	stdlib_basic3dInit000();
	easygl_easyglInit000();
	stb_image_componentsInit000();
	stb_image_readInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T1_;
	tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg* T2_;
	nimfr_("textures", "textures.nim");
nimRegisterGlobalMarker(TM_INbm9aJ9a9blRlORom2TaXUtg_4);
nimRegisterGlobalMarker(TM_INbm9aJ9a9blRlORom2TaXUtg_7);
nimRegisterGlobalMarker(TM_INbm9aJ9a9blRlORom2TaXUtg_10);
	nimln_(8, "textures.nim");
	T1_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
	T1_ = Dl_141765_(((int) 65535));
	T1_;
	nimln_(10, "textures.nim");
	screenWidth_vjbzgzYGWQy5ki2rtZ9cIPg = ((int) 800);
	nimln_(11, "textures.nim");
	screenHeight_kUdSBZ1Y71t0PBinc225wA = ((int) 600);
	nimln_(13, "textures.nim");
	window_7UKPy9bZBX2Sohrm5ymcfCA = Dl_142356_("Shaders", ((int) 100), ((int) 100), screenWidth_vjbzgzYGWQy5ki2rtZ9cIPg, screenHeight_kUdSBZ1Y71t0PBinc225wA, ((unsigned int) 34));
	nimln_(14, "textures.nim");
	T2_ = (tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg*)0;
	T2_ = Dl_142434_(window_7UKPy9bZBX2Sohrm5ymcfCA);
	T2_;
	nimln_(17, "textures.nim");
	nimLoadProcs0();
	nimln_(21, "textures.nim");
	ourShader_pwwci3JDoI3BLHc7foB76A = CreateAndLinkProgram_vn5ROZF0pfhPx6U9bF9ccGXw(((NimStringDesc*) &TM_INbm9aJ9a9blRlORom2TaXUtg_2), ((NimStringDesc*) &TM_INbm9aJ9a9blRlORom2TaXUtg_3), NIM_NIL);
	nimln_(24, "textures.nim");
	genericSeqAssign((&vertices_obvszk3Pq7O9cWcVznfC1VQ), TM_INbm9aJ9a9blRlORom2TaXUtg_5, (&NTI_4Xyxy0Om14N6K1l5e9bUPSQ_));
	nimln_(33, "textures.nim");
	if (indices_SbLaaOg6YSMYQi383iVLeg) { nimGCunrefNoCycle(indices_SbLaaOg6YSMYQi383iVLeg); indices_SbLaaOg6YSMYQi383iVLeg = NIM_NIL; }
	indices_SbLaaOg6YSMYQi383iVLeg = (tySequence_9bAGqSvkAaFL9bWjsEPslrFA*) newSeqRC1((&NTI_9bAGqSvkAaFL9bWjsEPslrFA_), 6);
	indices_SbLaaOg6YSMYQi383iVLeg->data[0] = ((NU32) 0);
	indices_SbLaaOg6YSMYQi383iVLeg->data[1] = ((NU32) 1);
	indices_SbLaaOg6YSMYQi383iVLeg->data[2] = ((NU32) 3);
	indices_SbLaaOg6YSMYQi383iVLeg->data[3] = ((NU32) 1);
	indices_SbLaaOg6YSMYQi383iVLeg->data[4] = ((NU32) 2);
	indices_SbLaaOg6YSMYQi383iVLeg->data[5] = ((NU32) 3);
	nimln_(39, "textures.nim");
	VAO_8RoCMJcu3R7ef4S4GTcnfg = GenVertexArray_y9aWBmx772xkm1fCOo2NcFAeasygl();
	nimln_(40, "textures.nim");
	VBO_goEXduuaoUdyW5sR7fyiWg = GenBuffer_xxU7oJIkwZkPfbkUj9aKWpgeasygl();
	nimln_(41, "textures.nim");
	EBO_eg09c4OZXlgDHEEdDD0UsRA = GenBuffer_xxU7oJIkwZkPfbkUj9aKWpgeasygl();
	nimln_(44, "textures.nim");
	BindVertexArray_1olxbPfcB1SGdKsshWP3wgeasygl(VAO_8RoCMJcu3R7ef4S4GTcnfg);
	nimln_(46, "textures.nim");
	BindBuffer_W9bN003jC8Uhvy4z5xdUL9bAeasygl(((tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw) 34962), VBO_goEXduuaoUdyW5sR7fyiWg);
	nimln_(47, "textures.nim");
	BufferData_9c9bFitUJKUzqcspXMNZg4Iwtextures(((tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw) 34962), vertices_obvszk3Pq7O9cWcVznfC1VQ->data, vertices_obvszk3Pq7O9cWcVznfC1VQ->Sup.len, ((tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA) 35044));
	nimln_(49, "textures.nim");
	BindBuffer_W9bN003jC8Uhvy4z5xdUL9bAeasygl(((tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw) 34963), EBO_eg09c4OZXlgDHEEdDD0UsRA);
	nimln_(50, "textures.nim");
	BufferData_NHhcuX9a476t2DF9ccAE29csQtextures(((tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw) 34963), indices_SbLaaOg6YSMYQi383iVLeg->data, indices_SbLaaOg6YSMYQi383iVLeg->Sup.len, ((tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA) 35044));
	nimln_(52, "textures.nim");
	VertexAttribPointer_rpmL9b1Xbhw9au2jacf9chz2geasygl(((NU32) 0), ((NI) 3), ((tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw) 5126), NIM_FALSE, ((NI32) 32), ((NI32) 0));
	nimln_(53, "textures.nim");
	EnableVertexAttribArray_xe9ai9b74zILHV5CMYQeQAVgeasygl(((NU32) 0));
	nimln_(55, "textures.nim");
	VertexAttribPointer_rpmL9b1Xbhw9au2jacf9chz2geasygl(((NU32) 1), ((NI) 3), ((tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw) 5126), NIM_FALSE, ((NI32) 32), ((NI32) 12));
	nimln_(56, "textures.nim");
	EnableVertexAttribArray_xe9ai9b74zILHV5CMYQeQAVgeasygl(((NU32) 1));
	nimln_(59, "textures.nim");
	VertexAttribPointer_rpmL9b1Xbhw9au2jacf9chz2geasygl(((NU32) 2), ((NI) 2), ((tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw) 5126), NIM_FALSE, ((NI32) 32), ((NI32) 24));
	nimln_(60, "textures.nim");
	EnableVertexAttribArray_xe9ai9b74zILHV5CMYQeQAVgeasygl(((NU32) 2));
	nimln_(62, "textures.nim");
	texture1_vhQZk02gBMTm9bM2Y319cvZQ = GenTexture_KDNM0klSr3qVvz89a9b0xoCw();
	nimln_(63, "textures.nim");
	BindTexture_psAXddCo1UfaZMOxWAy80Q(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), texture1_vhQZk02gBMTm9bM2Y319cvZQ);
	nimln_(64, "textures.nim");
	TexParameteri_k1oDC9bpuJWK3oPmF9cIROxw(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), ((tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw) 10242), ((NI32) 10497));
	nimln_(65, "textures.nim");
	TexParameteri_k1oDC9bpuJWK3oPmF9cIROxw(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), ((tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw) 10243), ((NI32) 10497));
	nimln_(67, "textures.nim");
	TexParameteri_k1oDC9bpuJWK3oPmF9cIROxw(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), ((tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw) 10241), ((NI32) 9729));
	nimln_(68, "textures.nim");
	TexParameteri_k1oDC9bpuJWK3oPmF9cIROxw(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), ((tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw) 10240), ((NI32) 9729));
	nimln_(73, "textures.nim");
	setFlipVerticallyOnLoad_ayevlb02tzQDH45TRoMJUg(NIM_TRUE);
	nimln_(74, "textures.nim");
	asgnRefNoCycle((void**) (&data_WWEHTX69am8YILp4n9auAmIQ), load_IpqKxisbLcaIMgU5vJeYeQ(((NimStringDesc*) &TM_INbm9aJ9a9blRlORom2TaXUtg_11), (&width_sXD3CLlh2pfMPS2H9cHfeLg), (&height_pWysFDIF9cSyeqEdmJajYTQ), (&channels_Yl9aiUtLUdJKOOzvkEnnJFg), ((NI) 0)));
	nimln_(76, "textures.nim");
	{
		NIM_BOOL T5_;
		NIM_BOOL T6_;
		NI T8_;
		T5_ = (NIM_BOOL)0;
		nimln_(378, "system.nim");
		nimln_(76, "textures.nim");
		T6_ = (NIM_BOOL)0;
		T6_ = eqeq__i5CVqMuqYwWXXhbrePT8aA(data_WWEHTX69am8YILp4n9auAmIQ, NIM_NIL);
		T5_ = !(T6_);
		if (!(T5_)) goto LA7_;
		nimln_(378, "system.nim");
		nimln_(76, "textures.nim");
		T8_ = (data_WWEHTX69am8YILp4n9auAmIQ ? data_WWEHTX69am8YILp4n9auAmIQ->Sup.len : 0);
		T5_ = !((T8_ == ((NI) 0)));
		LA7_: ;
		if (!T5_) goto LA9_;
		nimln_(77, "textures.nim");
		TexImage2D_7Lu1IWnN36sTJObNwvi7yQ(((tyEnum_TexImageTarget_4wNONQCfx9aiSc9avZaS5o1w) 3553), ((NI32) 0), ((tyEnum_TextureInternalFormat_JO6OJgblQDuq8JEmilKxEw) 6407), ((NI32)chckRange(width_sXD3CLlh2pfMPS2H9cHfeLg, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NI32)chckRange(height_pWysFDIF9cSyeqEdmJajYTQ, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((tyEnum_PixelDataFormat_jqJeBox56diuzpllVzXL8Q) 6407), ((tyEnum_PixelDataType_cEc9b7cEgtR9b0K320YQVELw) 5121), data_WWEHTX69am8YILp4n9auAmIQ->data, data_WWEHTX69am8YILp4n9auAmIQ->Sup.len);
		nimln_(78, "textures.nim");
		GenerateMipmap_iJouCAx7H7vAFe9cgWStrew(((tyEnum_MipmapTarget_SUlrCIDio0dfKLufGk9a2tg) 3553));
	}
	goto LA3_;
	LA9_: ;
	{
		nimln_(80, "textures.nim");
		printf("%s\015\012", ((NimStringDesc*) &TM_INbm9aJ9a9blRlORom2TaXUtg_12)? (((NimStringDesc*) &TM_INbm9aJ9a9blRlORom2TaXUtg_12))->data:"nil");
		fflush(stdout);
	}
	LA3_: ;
	nimln_(82, "textures.nim");
	texture2_YDuKjLLtNRCUFwFbvjoPHw = GenTexture_KDNM0klSr3qVvz89a9b0xoCw();
	nimln_(83, "textures.nim");
	BindTexture_psAXddCo1UfaZMOxWAy80Q(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), texture2_YDuKjLLtNRCUFwFbvjoPHw);
	nimln_(84, "textures.nim");
	TexParameteri_k1oDC9bpuJWK3oPmF9cIROxw(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), ((tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw) 10242), ((NI32) 10497));
	nimln_(85, "textures.nim");
	TexParameteri_k1oDC9bpuJWK3oPmF9cIROxw(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), ((tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw) 10243), ((NI32) 10497));
	nimln_(87, "textures.nim");
	TexParameteri_k1oDC9bpuJWK3oPmF9cIROxw(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), ((tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw) 10241), ((NI32) 9729));
	nimln_(88, "textures.nim");
	TexParameteri_k1oDC9bpuJWK3oPmF9cIROxw(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), ((tyEnum_TextureParameter_6qCMWukmxhQYvsra7e5aOw) 10240), ((NI32) 9729));
	nimln_(90, "textures.nim");
	asgnRefNoCycle((void**) (&data_WWEHTX69am8YILp4n9auAmIQ), load_IpqKxisbLcaIMgU5vJeYeQ(((NimStringDesc*) &TM_INbm9aJ9a9blRlORom2TaXUtg_13), (&width_sXD3CLlh2pfMPS2H9cHfeLg), (&height_pWysFDIF9cSyeqEdmJajYTQ), (&channels_Yl9aiUtLUdJKOOzvkEnnJFg), ((NI) 0)));
	nimln_(92, "textures.nim");
	{
		NIM_BOOL T14_;
		NIM_BOOL T15_;
		NI T17_;
		T14_ = (NIM_BOOL)0;
		nimln_(378, "system.nim");
		nimln_(92, "textures.nim");
		T15_ = (NIM_BOOL)0;
		T15_ = eqeq__i5CVqMuqYwWXXhbrePT8aA(data_WWEHTX69am8YILp4n9auAmIQ, NIM_NIL);
		T14_ = !(T15_);
		if (!(T14_)) goto LA16_;
		nimln_(378, "system.nim");
		nimln_(92, "textures.nim");
		T17_ = (data_WWEHTX69am8YILp4n9auAmIQ ? data_WWEHTX69am8YILp4n9auAmIQ->Sup.len : 0);
		T14_ = !((T17_ == ((NI) 0)));
		LA16_: ;
		if (!T14_) goto LA18_;
		nimln_(93, "textures.nim");
		TexImage2D_7Lu1IWnN36sTJObNwvi7yQ(((tyEnum_TexImageTarget_4wNONQCfx9aiSc9avZaS5o1w) 3553), ((NI32) 0), ((tyEnum_TextureInternalFormat_JO6OJgblQDuq8JEmilKxEw) 6407), ((NI32)chckRange(width_sXD3CLlh2pfMPS2H9cHfeLg, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NI32)chckRange(height_pWysFDIF9cSyeqEdmJajYTQ, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((tyEnum_PixelDataFormat_jqJeBox56diuzpllVzXL8Q) 6408), ((tyEnum_PixelDataType_cEc9b7cEgtR9b0K320YQVELw) 5121), data_WWEHTX69am8YILp4n9auAmIQ->data, data_WWEHTX69am8YILp4n9auAmIQ->Sup.len);
		nimln_(94, "textures.nim");
		GenerateMipmap_iJouCAx7H7vAFe9cgWStrew(((tyEnum_MipmapTarget_SUlrCIDio0dfKLufGk9a2tg) 3553));
	}
	goto LA12_;
	LA18_: ;
	{
		nimln_(96, "textures.nim");
		printf("%s\015\012", ((NimStringDesc*) &TM_INbm9aJ9a9blRlORom2TaXUtg_12)? (((NimStringDesc*) &TM_INbm9aJ9a9blRlORom2TaXUtg_12))->data:"nil");
		fflush(stdout);
	}
	LA12_: ;
	nimln_(98, "textures.nim");
	UseProgram_zLuRnlSabmGQB1f159beDeA_2easygl(ourShader_pwwci3JDoI3BLHc7foB76A);
	nimln_(99, "textures.nim");
	SetInt_TVl5u9c9caFJMWzPp8lSDH1A(ourShader_pwwci3JDoI3BLHc7foB76A, ((NimStringDesc*) &TM_INbm9aJ9a9blRlORom2TaXUtg_14), ((NI32) 1));
	nimln_(103, "textures.nim");
	evt_pPNt0Sf7d9abHQ9a7GrRW4OA = defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
	nimln_(104, "textures.nim");
	run_JZPBbfeDSYPZ5rtEvJtxPg = NIM_TRUE;
	nimln_(106, "textures.nim");
	glViewport_yDKviL1Jxz9cvMulIoNt7vQ(((NI32) 0), ((NI32) 0), screenWidth_vjbzgzYGWQy5ki2rtZ9cIPg, screenHeight_kUdSBZ1Y71t0PBinc225wA);
	{
		nimln_(108, "textures.nim");
		while (1) {
			if (!run_JZPBbfeDSYPZ5rtEvJtxPg) goto LA22;
			{
				nimln_(109, "textures.nim");
				while (1) {
					tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg T25_;
					NIM_BOOL T26_;
					T25_ = (tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg)0;
					T25_ = Dl_142605_((&evt_pPNt0Sf7d9abHQ9a7GrRW4OA));
					T26_ = (NIM_BOOL)0;
					T26_ = toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ(T25_);
					if (!T26_) goto LA24;
					nimln_(110, "textures.nim");
					{
						if (!(evt_pPNt0Sf7d9abHQ9a7GrRW4OA.kind == ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 256))) goto LA29_;
						nimln_(111, "textures.nim");
						run_JZPBbfeDSYPZ5rtEvJtxPg = NIM_FALSE;
						nimln_(112, "textures.nim");
						goto LA23;
					}
					LA29_: ;
					nimln_(113, "textures.nim");
					{
						if (!(evt_pPNt0Sf7d9abHQ9a7GrRW4OA.kind == ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 512))) goto LA33_;
						windowEvent_jAVoRfSLYjQCCiYeQXCoKw = 0;
						nimln_(114, "textures.nim");
						windowEvent_jAVoRfSLYjQCCiYeQXCoKw = ((tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA*) ((&evt_pPNt0Sf7d9abHQ9a7GrRW4OA)));
						nimln_(115, "textures.nim");
						{
							if (!((*windowEvent_jAVoRfSLYjQCCiYeQXCoKw).event == ((tyEnum_WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw) 5))) goto LA37_;
							newWidth_lVgBZdubJhDvEGjFqaKzCw = 0;
							nimln_(116, "textures.nim");
							newWidth_lVgBZdubJhDvEGjFqaKzCw = (*windowEvent_jAVoRfSLYjQCCiYeQXCoKw).data1;
							newHeight_mC8gViuxlihFtgGSJtVo6Q = 0;
							nimln_(117, "textures.nim");
							newHeight_mC8gViuxlihFtgGSJtVo6Q = (*windowEvent_jAVoRfSLYjQCCiYeQXCoKw).data2;
							nimln_(118, "textures.nim");
							glViewport_yDKviL1Jxz9cvMulIoNt7vQ(((NI32) 0), ((NI32) 0), newWidth_lVgBZdubJhDvEGjFqaKzCw, newHeight_mC8gViuxlihFtgGSJtVo6Q);
						}
						LA37_: ;
					}
					LA33_: ;
				} LA24: ;
			} LA23: ;
			nimln_(121, "textures.nim");
			ClearColor_dPsnFT23vDc9bue9bSM7F6dw(2.0000000000000001e-001, 2.9999999999999999e-001, 2.9999999999999999e-001, 1.0000000000000000e+000);
			nimln_(122, "textures.nim");
			Clear_oYYKmodfLpSojEpZtDQHrgeasygl(TM_INbm9aJ9a9blRlORom2TaXUtg_16, 1);
			nimln_(124, "textures.nim");
			ActiveTexture_X1xra1GiiRlEPfa1pegmSA(((tyEnum_TextureUnit_Pe1qRsFIu9a5dqer2eHdpAg) 33984));
			nimln_(125, "textures.nim");
			BindTexture_psAXddCo1UfaZMOxWAy80Q(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), texture1_vhQZk02gBMTm9bM2Y319cvZQ);
			nimln_(126, "textures.nim");
			ActiveTexture_X1xra1GiiRlEPfa1pegmSA(((tyEnum_TextureUnit_Pe1qRsFIu9a5dqer2eHdpAg) 33985));
			nimln_(127, "textures.nim");
			BindTexture_psAXddCo1UfaZMOxWAy80Q(((tyEnum_TextureTarget_r9bZqCEso5C37CtGBgWEDpA) 3553), texture2_YDuKjLLtNRCUFwFbvjoPHw);
			nimln_(129, "textures.nim");
			UseProgram_zLuRnlSabmGQB1f159beDeA_2easygl(ourShader_pwwci3JDoI3BLHc7foB76A);
			nimln_(130, "textures.nim");
			BindVertexArray_1olxbPfcB1SGdKsshWP3wgeasygl(VAO_8RoCMJcu3R7ef4S4GTcnfg);
			nimln_(131, "textures.nim");
			DrawElements_t1y9ax9cvJfzgyrfV2IPW85w(((tyEnum_DrawMode_AmhJunCRQ8PFJ9aloC9ag9bYQ) 4), ((NI) 6), ((tyEnum_IndexType_KuLW3epA7GK4gjJFmNlYtw) 5125), ((NI) 0));
			nimln_(132, "textures.nim");
			Dl_142456_(window_7UKPy9bZBX2Sohrm5ymcfCA);
		} LA22: ;
	}
	nimln_(134, "textures.nim");
	DeleteVertexArray_6Mddmv88ZGGy9atNA0qt9cSg(VAO_8RoCMJcu3R7ef4S4GTcnfg);
	nimln_(135, "textures.nim");
	DeleteBuffer_PXtHP5umfE4uietYmnGuRw(VBO_goEXduuaoUdyW5sR7fyiWg);
	nimln_(136, "textures.nim");
	DeleteBuffer_PXtHP5umfE4uietYmnGuRw(EBO_eg09c4OZXlgDHEEdDD0UsRA);
	nimln_(137, "textures.nim");
	destroy_sFvfWODyHxg46OuBtGyU8Qtextures(window_7UKPy9bZBX2Sohrm5ymcfCA);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, texturesDatInit000)(void) {
}

