/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim\lib -o C:\projects\easygl\examples\nimcache\easygl_shaders.o C:\projects\easygl\examples\nimcache\easygl_shaders.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w;
typedef struct tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_4Xyxy0Om14N6K1l5e9bUPSQ tySequence_4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug;
typedef struct tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA;
typedef NI32 tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw;
typedef N_CDECL_PTR(tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw, tyProc_fvOXafK39cW5YZA9b9bzinu9cw) (int flags);
typedef N_CDECL_PTR(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w*, tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg*, tyProc_A4TgaVzGkRyot8mrE1bD0g) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NU16 tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw;
typedef NU16 tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA;
typedef NU16 tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw;
typedef NI32 tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w;
typedef NU8 tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw[52];
struct tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
tyArray_Y1pDC6KIrpu9aJMBN9aOQMhw padding;
};
typedef NI32 tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg;
typedef N_CDECL_PTR(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg, tyProc_b9aXpKFbsyZ0PIk3aYRVCAA) (tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug* event);
typedef NU8 tyEnum_WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw;
struct tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA {
tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w kind;
NU32 timestamp;
NU32 windowID;
tyEnum_WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw event;
NU8 pad1;
NU8 pad2;
NU8 pad3;
int data1;
int data2;
};
typedef NU16 tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ;
typedef tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ tyArray_ue9bV4rvhyJDkh6kT7PhDLg[1];
typedef NU8 tyEnum_DrawMode_AmhJunCRQ8PFJ9aloC9ag9bYQ;
typedef N_CDECL_PTR(void, tyProc_T629bWTbvDFNyKAaO0BGGIQ) (tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
struct tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w {
char dummy;
};
struct tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg {
char dummy;
};
struct tySequence_4Xyxy0Om14N6K1l5e9bUPSQ {
  TGenericSeq Sup;
  NF32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimLoadProcs0)(void);
N_NIMCALL(NU32, CreateAndLinkProgram_vn5ROZF0pfhPx6U9bF9ccGXw)(NimStringDesc* vertexPath, NimStringDesc* fragmentPath, NimStringDesc* geometryPath);
static N_NIMCALL(void, Marker_tySequence_4Xyxy0Om14N6K1l5e9bUPSQ)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_LGbJoatyvo7aYvW5CmwMmg_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NU32, GenVertexArray_y9aWBmx772xkm1fCOo2NcFAeasygl)(void);
N_STDCALL(void, glGenVertexArrays_zvqeRPLD9c2eggqLYZ1r3Zg)(NI32 n, NU32* arrays);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NU32, GenBuffer_xxU7oJIkwZkPfbkUj9aKWpgeasygl)(void);
N_STDCALL(void, glGenBuffers_B9ax9aWnWORHtXpch5OZqE6g)(NI32 n, NU32* buffers);
static N_INLINE(void, BindVertexArray_1olxbPfcB1SGdKsshWP3wgeasygl)(NU32 vertexArray);
N_STDCALL(void, glBindVertexArray_DTfQaj6wT6HQ9c375GwSXmg)(NU32 array);
static N_INLINE(void, BindBuffer_W9bN003jC8Uhvy4z5xdUL9bAeasygl)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NU32 buffer);
N_STDCALL(void, glBindBuffer_3rtrqe5eYHMVBLzlqTY63w)(NU32 target, NU32 buffer);
static N_INLINE(void, BufferData_9c9bFitUJKUzqcspXMNZg4Iwshaders)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NF32* data, NI dataLen_0, tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA usage);
N_STDCALL(void, glBufferData_00Qu57bAXtAMX49bzkHe6aQ)(NU32 target, NI size, void* data, NU32 usage);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(void, VertexAttribPointer_rpmL9b1Xbhw9au2jacf9chz2geasygl)(NU32 index, NI size, tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw attribType, NIM_BOOL normalized, NI32 stride, NI32 pointer);
N_STDCALL(void, glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer);
static N_INLINE(void, EnableVertexAttribArray_xe9ai9b74zILHV5CMYQeQAVgeasygl)(NU32 indeX);
N_STDCALL(void, glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA)(NU32 index);
N_STDCALL(void, glViewport_yDKviL1Jxz9cvMulIoNt7vQ)(NI32 x, NI32 y, NI32 width, NI32 height);
N_NIMCALL(NIM_BOOL, toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ)(tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg some);
N_NIMCALL(void, ClearColor_dPsnFT23vDc9bue9bSM7F6dw)(NF32 r, NF32 g, NF32 b, NF32 a);
static N_INLINE(void, Clear_oYYKmodfLpSojEpZtDQHrgeasygl)(tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ* buffersToClear, NI buffersToClearLen_0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_STDCALL(void, glClear_ecjp09clx9c7t3uIhyfuACGQ)(NU32 mask);
static N_INLINE(void, UseProgram_zLuRnlSabmGQB1f159beDeA_2easygl)(NU32 program);
N_STDCALL(void, glUseProgram_bYudX2ps2dTBClLz2NbyzA_2)(NU32 program);
static N_INLINE(void, DrawArrays_mtLt6it7C9aWjwdUxksWRugeasygl)(tyEnum_DrawMode_AmhJunCRQ8PFJ9aloC9ag9bYQ mode, NI32 first, NI32 count);
N_STDCALL(void, glDrawArrays_Bw7cKcZtx9bAbZdj5Iw9af9ag)(NU32 mode, NI32 first, NI32 count);
N_NIMCALL(void, DeleteVertexArray_6Mddmv88ZGGy9atNA0qt9cSg)(NU32 vertexArray);
N_NIMCALL(void, DeleteBuffer_PXtHP5umfE4uietYmnGuRw)(NU32 buffer);
static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qshaders)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init000)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, opengl_openglInit000)(void);
NIM_EXTERNC N_NOINLINE(void, opengl_openglDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic3dInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_basic3dDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, easygl_easyglInit000)(void);
NIM_EXTERNC N_NOINLINE(void, easygl_easyglDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, shadersDatInit000)(void);
extern tyProc_fvOXafK39cW5YZA9b9bzinu9cw Dl_141765_;
int screenWidth_KjQl47yAkWMza586i9chO7Q;
int screenHeight_1oYKXZ4akx1UbIpEBnNqew;
tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window_ZR9bSEojdEP4LvYfvbH7Luw;
extern tyProc_1K9aSViCbSUpZMtRI9aw9a2Rg Dl_142356_;
extern tyProc_A4TgaVzGkRyot8mrE1bD0g Dl_142434_;
NU32 programId_tD2tgtiXjkjFEDcrD3QeCw;
tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* vertices_V9cSAsucnZ5gBmVTf3NDntQ;
extern TNimType NTI_C875xFvYpI7aGybrDGHIaQ_;
TNimType NTI_4Xyxy0Om14N6K1l5e9bUPSQ_;
NU32 VAO_UpgMBc9a9bHbfGnFIHUuYlxw;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NU32 VBO_CYVzKOdrDM4zR9cJo9aWoosA;
tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug evt_A9bEsTF0VT6WgDkaVkqaLFA;
extern tyObject_Event_Uzh9aP43ffUpM9aa6vZvNEug defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
NIM_BOOL run_g8qCp9cWyCOfXAz9bUFXESWg;
extern tyProc_b9aXpKFbsyZ0PIk3aYRVCAA Dl_142605_;
tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA* windowEvent_NpTDKUU6qVlpBoXu1GjB3Q;
int newWidth_DtfztjZB0DG9c9bUbZgTAO7Q;
int newHeight_x31uxG0LI67rhRBbtOgmNQ;
extern tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_142456_;
extern tyProc_T629bWTbvDFNyKAaO0BGGIQ Dl_142388_;
STRING_LITERAL(TM_LGbJoatyvo7aYvW5CmwMmg_2, "shaders/shaders.vert", 20);
STRING_LITERAL(TM_LGbJoatyvo7aYvW5CmwMmg_3, "shaders/shaders.frag", 20);
NIM_CONST struct {
  TGenericSeq Sup;
  NF32 data[18];
} TM_LGbJoatyvo7aYvW5CmwMmg_6 = {{18, 18}, {5.0000000000000000e-001f,
-5.0000000000000000e-001,
0.0f,
1.0000000000000000e+000f,
0.0f,
0.0f,
-5.0000000000000000e-001,
-5.0000000000000000e-001,
0.0f,
0.0f,
1.0000000000000000e+000f,
0.0f,
0.0f,
5.0000000000000000e-001f,
0.0f,
0.0f,
0.0f,
1.0000000000000000e+000f}};
NIM_CONST tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* TM_LGbJoatyvo7aYvW5CmwMmg_5 = ((tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)&TM_LGbJoatyvo7aYvW5CmwMmg_6);
NIM_CONST tyArray_ue9bV4rvhyJDkh6kT7PhDLg TM_LGbJoatyvo7aYvW5CmwMmg_9 = {((tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ) 16384)}
;
static N_NIMCALL(void, Marker_tySequence_4Xyxy0Om14N6K1l5e9bUPSQ)(void* p, NI op) {
	tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* a;
	NI T1_;
	a = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, TM_LGbJoatyvo7aYvW5CmwMmg_4)(void) {
	nimGCvisit((void*)vertices_V9cSAsucnZ5gBmVTf3NDntQ, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NU32, GenVertexArray_y9aWBmx772xkm1fCOo2NcFAeasygl)(void) {
	NU32 result;
	nimfr_("GenVertexArray", "easygl.nim");
	result = (NU32)0;
	nimln_(232, "easygl.nim");
	glGenVertexArrays_zvqeRPLD9c2eggqLYZ1r3Zg(((NI32) 1), ((NU32*) ((&result))));
	popFrame();
	return result;
}

static N_INLINE(NU32, GenBuffer_xxU7oJIkwZkPfbkUj9aKWpgeasygl)(void) {
	NU32 result;
	nimfr_("GenBuffer", "easygl.nim");
	result = (NU32)0;
	nimln_(98, "easygl.nim");
	glGenBuffers_B9ax9aWnWORHtXpch5OZqE6g(((NI32) 1), ((NU32*) ((&result))));
	popFrame();
	return result;
}

static N_INLINE(void, BindVertexArray_1olxbPfcB1SGdKsshWP3wgeasygl)(NU32 vertexArray) {
	nimfr_("BindVertexArray", "easygl.nim");
	nimln_(246, "easygl.nim");
	glBindVertexArray_DTfQaj6wT6HQ9c375GwSXmg(vertexArray);
	popFrame();
}

static N_INLINE(void, BindBuffer_W9bN003jC8Uhvy4z5xdUL9bAeasygl)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NU32 buffer) {
	nimfr_("BindBuffer", "easygl.nim");
	nimln_(112, "easygl.nim");
	glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) (target)), buffer);
	popFrame();
}

static N_INLINE(void, BufferData_9c9bFitUJKUzqcspXMNZg4Iwshaders)(tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw target, NF32* data, NI dataLen_0, tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA usage) {
	NI TM_LGbJoatyvo7aYvW5CmwMmg_7;
	nimfr_("BufferData", "easygl.nim");
	nimln_(115, "easygl.nim");
	TM_LGbJoatyvo7aYvW5CmwMmg_7 = mulInt(dataLen_0, ((NI) 4));
	glBufferData_00Qu57bAXtAMX49bzkHe6aQ(((NU32) (target)), (NI)(TM_LGbJoatyvo7aYvW5CmwMmg_7), ((void*) (data)), ((NU32) (usage)));
	popFrame();
}

static N_INLINE(void, VertexAttribPointer_rpmL9b1Xbhw9au2jacf9chz2geasygl)(NU32 index, NI size, tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw attribType, NIM_BOOL normalized, NI32 stride, NI32 pointer) {
	nimfr_("VertexAttribPointer", "easygl.nim");
	nimln_(250, "easygl.nim");
	glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(index, ((NI32) (size)), ((NU32) (attribType)), normalized, stride, ((void*) (pointer)));
	popFrame();
}

static N_INLINE(void, EnableVertexAttribArray_xe9ai9b74zILHV5CMYQeQAVgeasygl)(NU32 indeX) {
	nimfr_("EnableVertexAttribArray", "easygl.nim");
	nimln_(253, "easygl.nim");
	glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(indeX);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, Clear_oYYKmodfLpSojEpZtDQHrgeasygl)(tyEnum_ClearBufferMask_lO6Dt9aokgt9cH8rSDGYbX9aQ* buffersToClear, NI buffersToClearLen_0) {
	NU32 mask;
	nimfr_("Clear", "easygl.nim");
	nimln_(265, "easygl.nim");
	if ((NU)(((NI) 0)) >= (NU)(buffersToClearLen_0)) raiseIndexError();
	mask = ((NU32) (buffersToClear[((NI) 0)]));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(266, "easygl.nim");
		colontmp_ = subInt(buffersToClearLen_0, 1);
		nimln_(1973, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1974, "system.nim");
			while (1) {
				NI TM_LGbJoatyvo7aYvW5CmwMmg_8;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1975, "system.nim");
				i = res;
				nimln_(267, "easygl.nim");
				if ((NU)(i) >= (NU)(buffersToClearLen_0)) raiseIndexError();
				mask = (unsigned int)(mask | ((NU32) (buffersToClear[i])));
				nimln_(1976, "system.nim");
				TM_LGbJoatyvo7aYvW5CmwMmg_8 = addInt(res, ((NI) 1));
				res = (NI)(TM_LGbJoatyvo7aYvW5CmwMmg_8);
			} LA3: ;
		}
	}
	nimln_(268, "easygl.nim");
	glClear_ecjp09clx9c7t3uIhyfuACGQ(mask);
	popFrame();
}

static N_INLINE(void, UseProgram_zLuRnlSabmGQB1f159beDeA_2easygl)(NU32 program) {
	nimfr_("UseProgram", "easygl.nim");
	nimln_(200, "easygl.nim");
	glUseProgram_bYudX2ps2dTBClLz2NbyzA_2(program);
	popFrame();
}

static N_INLINE(void, DrawArrays_mtLt6it7C9aWjwdUxksWRugeasygl)(tyEnum_DrawMode_AmhJunCRQ8PFJ9aloC9ag9bYQ mode, NI32 first, NI32 count) {
	nimfr_("DrawArrays", "easygl.nim");
	nimln_(256, "easygl.nim");
	glDrawArrays_Bw7cKcZtx9bAbZdj5Iw9af9ag(((NU32) (mode)), first, count);
	popFrame();
}

static N_INLINE(void, destroy_sFvfWODyHxg46OuBtGyU8Qshaders)(tyObject_WindowPtrcolonObjectType__8bMU2xl1xmmMvYcskTOB4w* window) {
	nimfr_("destroy", "sdl2.nim");
	nimln_(1742, "sdl2.nim");
	Dl_142388_(window);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	sdl2_sdl2DatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	opengl_openglDatInit000();
	stdlib_basic2dDatInit000();
	stdlib_basic3dDatInit000();
	easygl_easyglDatInit000();
	shadersDatInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	sdl2_sdl2Init000();
	stdlib_sequtilsInit000();
	stdlib_dynlibInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	opengl_openglInit000();
	stdlib_basic2dInit000();
	stdlib_basic3dInit000();
	easygl_easyglInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw T1_;
	tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg* T2_;
	nimfr_("shaders", "shaders.nim");
nimRegisterGlobalMarker(TM_LGbJoatyvo7aYvW5CmwMmg_4);
	nimln_(8, "shaders.nim");
	T1_ = (tyEnum_SDL_Return_8wc8or7UFANAtbisKJq7lw)0;
	T1_ = Dl_141765_(((int) 65535));
	T1_;
	nimln_(10, "shaders.nim");
	screenWidth_KjQl47yAkWMza586i9chO7Q = ((int) 800);
	nimln_(11, "shaders.nim");
	screenHeight_1oYKXZ4akx1UbIpEBnNqew = ((int) 600);
	nimln_(13, "shaders.nim");
	window_ZR9bSEojdEP4LvYfvbH7Luw = Dl_142356_("Shaders", ((int) 100), ((int) 100), screenWidth_KjQl47yAkWMza586i9chO7Q, screenHeight_1oYKXZ4akx1UbIpEBnNqew, ((unsigned int) 34));
	nimln_(14, "shaders.nim");
	T2_ = (tyObject_GlContextPtrcolonObjectType__RFk4O9aogXphw3vfXrOizCg*)0;
	T2_ = Dl_142434_(window_ZR9bSEojdEP4LvYfvbH7Luw);
	T2_;
	nimln_(17, "shaders.nim");
	nimLoadProcs0();
	nimln_(21, "shaders.nim");
	programId_tD2tgtiXjkjFEDcrD3QeCw = CreateAndLinkProgram_vn5ROZF0pfhPx6U9bF9ccGXw(((NimStringDesc*) &TM_LGbJoatyvo7aYvW5CmwMmg_2), ((NimStringDesc*) &TM_LGbJoatyvo7aYvW5CmwMmg_3), NIM_NIL);
	nimln_(24, "shaders.nim");
	genericSeqAssign((&vertices_V9cSAsucnZ5gBmVTf3NDntQ), TM_LGbJoatyvo7aYvW5CmwMmg_5, (&NTI_4Xyxy0Om14N6K1l5e9bUPSQ_));
	nimln_(31, "shaders.nim");
	VAO_UpgMBc9a9bHbfGnFIHUuYlxw = GenVertexArray_y9aWBmx772xkm1fCOo2NcFAeasygl();
	nimln_(32, "shaders.nim");
	VBO_CYVzKOdrDM4zR9cJo9aWoosA = GenBuffer_xxU7oJIkwZkPfbkUj9aKWpgeasygl();
	nimln_(35, "shaders.nim");
	BindVertexArray_1olxbPfcB1SGdKsshWP3wgeasygl(VAO_UpgMBc9a9bHbfGnFIHUuYlxw);
	nimln_(37, "shaders.nim");
	BindBuffer_W9bN003jC8Uhvy4z5xdUL9bAeasygl(((tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw) 34962), VBO_CYVzKOdrDM4zR9cJo9aWoosA);
	nimln_(38, "shaders.nim");
	BufferData_9c9bFitUJKUzqcspXMNZg4Iwshaders(((tyEnum_BufferTarget_ErfFU3mi5ovMsHV4URfCgw) 34962), vertices_V9cSAsucnZ5gBmVTf3NDntQ->data, vertices_V9cSAsucnZ5gBmVTf3NDntQ->Sup.len, ((tyEnum_BufferDataUsage_JzOeul0QG8UdVnNILz38YA) 35044));
	nimln_(40, "shaders.nim");
	VertexAttribPointer_rpmL9b1Xbhw9au2jacf9chz2geasygl(((NU32) 0), ((NI) 3), ((tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw) 5126), NIM_FALSE, ((NI32) 24), ((NI32) 0));
	nimln_(41, "shaders.nim");
	EnableVertexAttribArray_xe9ai9b74zILHV5CMYQeQAVgeasygl(((NU32) 0));
	nimln_(43, "shaders.nim");
	VertexAttribPointer_rpmL9b1Xbhw9au2jacf9chz2geasygl(((NU32) 1), ((NI) 3), ((tyEnum_VertexAttribType_bs3Im7IMiwnCiTE9bMx9cjOw) 5126), NIM_FALSE, ((NI32) 24), ((NI32) 12));
	nimln_(44, "shaders.nim");
	EnableVertexAttribArray_xe9ai9b74zILHV5CMYQeQAVgeasygl(((NU32) 1));
	nimln_(48, "shaders.nim");
	evt_A9bEsTF0VT6WgDkaVkqaLFA = defaultEvent_LbtYyFPe9bpTC9bKZ8rWJeKQ;
	nimln_(49, "shaders.nim");
	run_g8qCp9cWyCOfXAz9bUFXESWg = NIM_TRUE;
	nimln_(51, "shaders.nim");
	glViewport_yDKviL1Jxz9cvMulIoNt7vQ(((NI32) 0), ((NI32) 0), screenWidth_KjQl47yAkWMza586i9chO7Q, screenHeight_1oYKXZ4akx1UbIpEBnNqew);
	{
		nimln_(53, "shaders.nim");
		while (1) {
			if (!run_g8qCp9cWyCOfXAz9bUFXESWg) goto LA4;
			{
				nimln_(54, "shaders.nim");
				while (1) {
					tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg T7_;
					NIM_BOOL T8_;
					T7_ = (tyEnum_Bool32_lrv4aZgVTmBUYdrYUkLMlg)0;
					T7_ = Dl_142605_((&evt_A9bEsTF0VT6WgDkaVkqaLFA));
					T8_ = (NIM_BOOL)0;
					T8_ = toBool_3fq5Y9cfgYx8q7J9ba6TTYbQ(T7_);
					if (!T8_) goto LA6;
					nimln_(55, "shaders.nim");
					{
						if (!(evt_A9bEsTF0VT6WgDkaVkqaLFA.kind == ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 256))) goto LA11_;
						nimln_(56, "shaders.nim");
						run_g8qCp9cWyCOfXAz9bUFXESWg = NIM_FALSE;
						nimln_(57, "shaders.nim");
						goto LA5;
					}
					LA11_: ;
					nimln_(58, "shaders.nim");
					{
						if (!(evt_A9bEsTF0VT6WgDkaVkqaLFA.kind == ((tyEnum_EventType_9ayvRjKFMoE6pV9bOp5OUI5w) 512))) goto LA15_;
						windowEvent_NpTDKUU6qVlpBoXu1GjB3Q = 0;
						nimln_(59, "shaders.nim");
						windowEvent_NpTDKUU6qVlpBoXu1GjB3Q = ((tyObject_WindowEventObj_d6XCemaEKzK59bxf1YxrwlA*) ((&evt_A9bEsTF0VT6WgDkaVkqaLFA)));
						nimln_(60, "shaders.nim");
						{
							if (!((*windowEvent_NpTDKUU6qVlpBoXu1GjB3Q).event == ((tyEnum_WindowEventID_qlyMtQ19b0uMsXgE0vQ3Diw) 5))) goto LA19_;
							newWidth_DtfztjZB0DG9c9bUbZgTAO7Q = 0;
							nimln_(61, "shaders.nim");
							newWidth_DtfztjZB0DG9c9bUbZgTAO7Q = (*windowEvent_NpTDKUU6qVlpBoXu1GjB3Q).data1;
							newHeight_x31uxG0LI67rhRBbtOgmNQ = 0;
							nimln_(62, "shaders.nim");
							newHeight_x31uxG0LI67rhRBbtOgmNQ = (*windowEvent_NpTDKUU6qVlpBoXu1GjB3Q).data2;
							nimln_(63, "shaders.nim");
							glViewport_yDKviL1Jxz9cvMulIoNt7vQ(((NI32) 0), ((NI32) 0), newWidth_DtfztjZB0DG9c9bUbZgTAO7Q, newHeight_x31uxG0LI67rhRBbtOgmNQ);
						}
						LA19_: ;
					}
					LA15_: ;
				} LA6: ;
			} LA5: ;
			nimln_(66, "shaders.nim");
			ClearColor_dPsnFT23vDc9bue9bSM7F6dw(2.0000000000000001e-001, 2.9999999999999999e-001, 2.9999999999999999e-001, 1.0000000000000000e+000);
			nimln_(67, "shaders.nim");
			Clear_oYYKmodfLpSojEpZtDQHrgeasygl(TM_LGbJoatyvo7aYvW5CmwMmg_9, 1);
			nimln_(68, "shaders.nim");
			UseProgram_zLuRnlSabmGQB1f159beDeA_2easygl(programId_tD2tgtiXjkjFEDcrD3QeCw);
			nimln_(69, "shaders.nim");
			BindVertexArray_1olxbPfcB1SGdKsshWP3wgeasygl(VAO_UpgMBc9a9bHbfGnFIHUuYlxw);
			nimln_(70, "shaders.nim");
			DrawArrays_mtLt6it7C9aWjwdUxksWRugeasygl(((tyEnum_DrawMode_AmhJunCRQ8PFJ9aloC9ag9bYQ) 4), ((NI32) 0), ((NI32) 3));
			nimln_(71, "shaders.nim");
			Dl_142456_(window_ZR9bSEojdEP4LvYfvbH7Luw);
		} LA4: ;
	}
	nimln_(73, "shaders.nim");
	DeleteVertexArray_6Mddmv88ZGGy9atNA0qt9cSg(VAO_UpgMBc9a9bHbfGnFIHUuYlxw);
	nimln_(74, "shaders.nim");
	DeleteBuffer_PXtHP5umfE4uietYmnGuRw(VBO_CYVzKOdrDM4zR9cJo9aWoosA);
	nimln_(75, "shaders.nim");
	destroy_sFvfWODyHxg46OuBtGyU8Qshaders(window_ZR9bSEojdEP4LvYfvbH7Luw);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, shadersDatInit000)(void) {
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.size = sizeof(tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*);
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.kind = 24;
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.base = (&NTI_C875xFvYpI7aGybrDGHIaQ_);
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.flags = 2;
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.marker = Marker_tySequence_4Xyxy0Om14N6K1l5e9bUPSQ;
}

