/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim\lib -o C:\projects\easygl\examples\nimcache\stb_image_read.o C:\projects\easygl\examples\nimcache\stb_image_read.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ tySequence_6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_uFLLGQVsiasALrzzzvqnZw tySequence_uFLLGQVsiasALrzzzvqnZw;
typedef struct tySequence_4Xyxy0Om14N6K1l5e9bUPSQ tySequence_4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ {
  Exception Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
struct tySequence_uFLLGQVsiasALrzzzvqnZw {
  TGenericSeq Sup;
  NU16 data[SEQ_DECL_SIZE];
};
struct tySequence_4Xyxy0Om14N6K1l5e9bUPSQ {
  TGenericSeq Sup;
  NF32 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, failureReason_jGKpadXTf7KJCfBI03WXEg)(void);
N_NIMCALL(NCSTRING, stbi_failure_reason)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*, load_IpqKxisbLcaIMgU5vJeYeQ)(NimStringDesc* filename, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_NIMCALL(unsigned char*, stbi_load)(NCSTRING filename, int* x, int* y, int* channels_in_file, int desired_channels);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_nkDbPegaPPXcgyPJXzLmBg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_NIMCALL(void, Marker_tySequence_6H5Oh5UUvVCLiakt9aTwtUQ)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, stbi_image_free)(void* retval_from_stbi_load);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*, loadFromMemory_Eyj9cclBxuzZTHaC4s9ad5Dg)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_NIMCALL(unsigned char*, stbi_load_from_memory)(unsigned char* buffer, int len, int* x, int* y, int* channels_in_file, int desired_channels);
N_NIMCALL(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*, loadFromFile_iAJEfV3InOTA4koYEonRfg)(FILE* f, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_NIMCALL(unsigned char*, stbi_load_from_file)(FILE* f, int* x, int* y, int* channels_in_file, int desired_channels);
N_NIMCALL(tySequence_uFLLGQVsiasALrzzzvqnZw*, load16_86k4H1fF358yUVxopsDgag)(NimStringDesc* filename, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_NIMCALL(unsigned short*, stbi_load_16)(NCSTRING filename, int* x, int* y, int* channels_in_file, int desired_channels);
static N_NIMCALL(void, Marker_tySequence_uFLLGQVsiasALrzzzvqnZw)(void* p, NI op);
N_NIMCALL(tySequence_uFLLGQVsiasALrzzzvqnZw*, loadFromFile16_24Bp3s4ROGXwM0hgUpC4hg)(FILE* f, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_NIMCALL(tySequence_uFLLGQVsiasALrzzzvqnZw*, load16FromMemory_qZOJzYOLYDveos6SERzbNQ)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_NIMCALL(unsigned short*, stbi_load_16_from_memory)(unsigned char* buffer, int len, int* x, int* y, int* channels_in_file, int desired_channels);
N_NIMCALL(tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*, loadF_y5tlrnRToj29aTOStIISTZQ)(NimStringDesc* filename, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_NIMCALL(float*, stbi_loadf)(NCSTRING filename, int* x, int* y, int* channels_in_file, int desired_channels);
static N_NIMCALL(void, Marker_tySequence_4Xyxy0Om14N6K1l5e9bUPSQ)(void* p, NI op);
N_NIMCALL(tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*, loadFFromMemory_SNNFUvHzPQ65cEa8VGkWCg)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_NIMCALL(float*, stbi_loadf_from_memory)(unsigned char* buffer, int len, int* x, int* y, int* channels_in_file, int desired_channels);
N_NIMCALL(tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*, loadFFromFile_34hrADNf1JOeF51H4MjPVg)(FILE* f, NI* x, NI* y, NI* channels_in_file, NI desired_channels);
N_NIMCALL(float*, stbi_loadf_from_file)(FILE* f, int* x, int* y, int* channels_in_file, int desired_channels);
N_NIMCALL(void, HDRToLDRGamma_Lsh39b9bxIV9a1rJgMKoM8fTA)(NF gamma);
N_NIMCALL(void, stbi_hdr_to_ldr_gamma)(float gamma);
N_NIMCALL(void, HDRToLDRScale_x36tyiHIpnQez4k8tcOfug)(NF scale);
N_NIMCALL(void, stbi_hdr_to_ldr_scale)(float scale);
N_NIMCALL(void, LDRToHDRGamma_Lsh39b9bxIV9a1rJgMKoM8fTA_2)(NF gamma);
N_NIMCALL(void, stbi_ldr_to_hdr_gamma)(float gamma);
N_NIMCALL(void, LDRToHDRScale_x36tyiHIpnQez4k8tcOfug_2)(NF scale);
N_NIMCALL(void, stbi_ldr_to_hdr_scale)(float scale);
N_NIMCALL(NIM_BOOL, isHDRFromMemory_mzZeUpW0Sh5x9cxIb9crdrog)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer);
N_NIMCALL(int, stbi_is_hdr_from_memory)(unsigned char* buffer, int len);
N_NIMCALL(NIM_BOOL, isHDR_ZQioKayM35gE9b9bVR9auSaWw)(NimStringDesc* filename);
N_NIMCALL(int, stbi_is_hdr)(NCSTRING filename);
N_NIMCALL(NIM_BOOL, isHDRFromFile_Ea70oRc5oVycZj7ta4wzwQ)(FILE* f);
N_NIMCALL(int, stbi_is_hdr_from_file)(FILE* f);
N_NIMCALL(NIM_BOOL, infoFromMemory_u8l9b9c8SKg4gdKhVXKVP9blw)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer, NI* x, NI* y, NI* comp);
N_NIMCALL(int, stbi_info_from_memory)(unsigned char* buffer, int len, int* x, int* y, int* comp);
N_NIMCALL(NIM_BOOL, info_VjXaJL7e9cMuRxP64g4KgaQ)(NimStringDesc* filename, NI* x, NI* y, NI* comp);
N_NIMCALL(int, stbi_info)(NCSTRING filename, int* x, int* y, int* comp);
N_NIMCALL(NIM_BOOL, infoFromFile_UGn9aG9bLDjdc7nonQQPq9b6Q)(FILE* f, NI* x, NI* y, NI* comp);
N_NIMCALL(int, stbi_info_from_file)(FILE* f, int* x, int* y, int* comp);
N_NIMCALL(void, setUnpremultiplyOnLoad_n7srZhNnr2VA69cDLKfieow)(NIM_BOOL unpremultiply);
N_NIMCALL(void, stbi_set_unpremultiply_on_load)(int flag_true_if_should_unpremultiply);
N_NIMCALL(void, convertIPhonePNGToRGB_689aweJ9cfBKRoqe4WZmyR7A)(NIM_BOOL convert);
N_NIMCALL(void, stbi_convert_iphone_png_to_rgb)(int flag_true_if_should_convert);
N_NIMCALL(void, setFlipVerticallyOnLoad_ayevlb02tzQDH45TRoMJUg)(NIM_BOOL flip);
N_NIMCALL(void, stbi_set_flip_vertically_on_load)(int flag_true_if_should_flip);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_;
TNimType NTI_nkDbPegaPPXcgyPJXzLmBg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_k3HXouOuhqAKq0dx450lXQ_;
TNimType NTI_6H5Oh5UUvVCLiakt9aTwtUQ_;
extern TNimType NTI_M4na42GvebBMnI5wV9cYMxg_;
TNimType NTI_uFLLGQVsiasALrzzzvqnZw_;
extern TNimType NTI_C875xFvYpI7aGybrDGHIaQ_;
TNimType NTI_4Xyxy0Om14N6K1l5e9bUPSQ_;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NimStringDesc*, failureReason_jGKpadXTf7KJCfBI03WXEg)(void) {
	NimStringDesc* result;
	NCSTRING T1_;
	nimfr_("failureReason", "read.nim");
{	result = (NimStringDesc*)0;
	nimln_(39, "read.nim");
	T1_ = (NCSTRING)0;
	T1_ = stbi_failure_reason();
	result = cstrToNimstr(T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tyRef_nkDbPegaPPXcgyPJXzLmBg)(void* p, NI op) {
	tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* a;
	a = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tySequence_6H5Oh5UUvVCLiakt9aTwtUQ)(void* p, NI op) {
	tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* a;
	NI T1_;
	a = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*)p;
	T1_ = (NI)0;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

N_NIMCALL(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*, load_IpqKxisbLcaIMgU5vJeYeQ)(NimStringDesc* filename, NI* x, NI* y, NI* channels_in_file, NI desired_channels) {
	tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* result;
	int width;
	int height;
	int components;
	unsigned char* data;
	tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* pixelData;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_2;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_3;
	NI T5_;
	nimfr_("load", "read.nim");
{	result = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*)0;
	width = (int)0;
	height = (int)0;
	components = (int)0;
	nimln_(87, "read.nim");
	data = stbi_load(filename->data, (&width), (&height), (&components), ((int)chckRange(desired_channels, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln_(90, "read.nim");
	{
		tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* e;
		if (!(data == NIM_NIL)) goto LA3_;
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*) newObj((&NTI_nkDbPegaPPXcgyPJXzLmBg_), sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ));
		(*e).Sup.Sup.m_type = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
		nimln_(91, "read.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.message), failureReason_jGKpadXTf7KJCfBI03WXEg());
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(91, "read.nim");
		raiseException((Exception*)e, "STBIException");
	}
	LA3_: ;
	nimln_(94, "read.nim");
	(*x) = ((NI) (width));
	nimln_(95, "read.nim");
	(*y) = ((NI) (height));
	nimln_(96, "read.nim");
	(*channels_in_file) = ((NI) (components));
	pixelData = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*)0;
	nimln_(100, "read.nim");
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_2 = mulInt((*x), (*y));
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_3 = mulInt((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_2), (*channels_in_file));
	pixelData = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*) newSeq((&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_), ((NI)chckRange((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_3), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(101, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(pixelData->Sup.len)) raiseIndexError();
	T5_ = (pixelData ? pixelData->Sup.len : 0);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&pixelData->data[((NI) 0)]))), ((void*) (data)), ((NI)chckRange(T5_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(104, "read.nim");
	stbi_image_free(((void*) (data)));
	nimln_(106, "read.nim");
	genericSeqAssign((&result), pixelData, (&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*, loadFromMemory_Eyj9cclBxuzZTHaC4s9ad5Dg)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer, NI* x, NI* y, NI* channels_in_file, NI desired_channels) {
	tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* result;
	unsigned char* castedBuffer;
	int width;
	int height;
	int components;
	unsigned char* data;
	NI T1_;
	tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* pixelData;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_4;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_5;
	NI T6_;
	nimfr_("loadFromMemory", "read.nim");
{	result = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*)0;
	nimln_(119, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(buffer->Sup.len)) raiseIndexError();
	castedBuffer = ((unsigned char*) ((&buffer->data[((NI) 0)])));
	width = (int)0;
	height = (int)0;
	components = (int)0;
	nimln_(127, "read.nim");
	T1_ = (buffer ? buffer->Sup.len : 0);
	data = stbi_load_from_memory(castedBuffer, ((int)chckRange(T1_, ((int) (-2147483647 -1)), ((int) 2147483647))), (&width), (&height), (&components), ((int)chckRange(desired_channels, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln_(130, "read.nim");
	{
		tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* e;
		if (!(data == NIM_NIL)) goto LA4_;
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*) newObj((&NTI_nkDbPegaPPXcgyPJXzLmBg_), sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ));
		(*e).Sup.Sup.m_type = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
		nimln_(131, "read.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.message), failureReason_jGKpadXTf7KJCfBI03WXEg());
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(131, "read.nim");
		raiseException((Exception*)e, "STBIException");
	}
	LA4_: ;
	nimln_(134, "read.nim");
	(*x) = ((NI) (width));
	nimln_(135, "read.nim");
	(*y) = ((NI) (height));
	nimln_(136, "read.nim");
	(*channels_in_file) = ((NI) (components));
	pixelData = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*)0;
	nimln_(140, "read.nim");
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_4 = mulInt((*x), (*y));
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_5 = mulInt((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_4), (*channels_in_file));
	pixelData = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*) newSeq((&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_), ((NI)chckRange((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_5), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(141, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(pixelData->Sup.len)) raiseIndexError();
	T6_ = (pixelData ? pixelData->Sup.len : 0);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&pixelData->data[((NI) 0)]))), ((void*) (data)), ((NI)chckRange(T6_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(144, "read.nim");
	stbi_image_free(((void*) (data)));
	nimln_(146, "read.nim");
	genericSeqAssign((&result), pixelData, (&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*, loadFromFile_iAJEfV3InOTA4koYEonRfg)(FILE* f, NI* x, NI* y, NI* channels_in_file, NI desired_channels) {
	tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* result;
	int width;
	int height;
	int components;
	unsigned char* data;
	tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* pixelData;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_6;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_7;
	NI T5_;
	nimfr_("loadFromFile", "read.nim");
{	result = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*)0;
	width = (int)0;
	height = (int)0;
	components = (int)0;
	nimln_(164, "read.nim");
	data = stbi_load_from_file(f, (&width), (&height), (&components), ((int)chckRange(desired_channels, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln_(167, "read.nim");
	{
		tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* e;
		if (!(data == NIM_NIL)) goto LA3_;
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*) newObj((&NTI_nkDbPegaPPXcgyPJXzLmBg_), sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ));
		(*e).Sup.Sup.m_type = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
		nimln_(168, "read.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.message), failureReason_jGKpadXTf7KJCfBI03WXEg());
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(168, "read.nim");
		raiseException((Exception*)e, "STBIException");
	}
	LA3_: ;
	nimln_(171, "read.nim");
	(*x) = ((NI) (width));
	nimln_(172, "read.nim");
	(*y) = ((NI) (height));
	nimln_(173, "read.nim");
	(*channels_in_file) = ((NI) (components));
	pixelData = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*)0;
	nimln_(177, "read.nim");
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_6 = mulInt((*x), (*y));
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_7 = mulInt((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_6), (*channels_in_file));
	pixelData = (tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*) newSeq((&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_), ((NI)chckRange((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_7), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(178, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(pixelData->Sup.len)) raiseIndexError();
	T5_ = (pixelData ? pixelData->Sup.len : 0);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&pixelData->data[((NI) 0)]))), ((void*) (data)), ((NI)chckRange(T5_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(181, "read.nim");
	stbi_image_free(((void*) (data)));
	nimln_(183, "read.nim");
	genericSeqAssign((&result), pixelData, (&NTI_6H5Oh5UUvVCLiakt9aTwtUQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_uFLLGQVsiasALrzzzvqnZw)(void* p, NI op) {
	tySequence_uFLLGQVsiasALrzzzvqnZw* a;
	NI T1_;
	a = (tySequence_uFLLGQVsiasALrzzzvqnZw*)p;
	T1_ = (NI)0;
}

N_NIMCALL(tySequence_uFLLGQVsiasALrzzzvqnZw*, load16_86k4H1fF358yUVxopsDgag)(NimStringDesc* filename, NI* x, NI* y, NI* channels_in_file, NI desired_channels) {
	tySequence_uFLLGQVsiasALrzzzvqnZw* result;
	int width;
	int height;
	int components;
	unsigned short* data;
	tySequence_uFLLGQVsiasALrzzzvqnZw* pixelData;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_8;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_9;
	NI T5_;
	nimfr_("load16", "read.nim");
{	result = (tySequence_uFLLGQVsiasALrzzzvqnZw*)0;
	width = (int)0;
	height = (int)0;
	components = (int)0;
	nimln_(230, "read.nim");
	data = stbi_load_16(filename->data, (&width), (&height), (&components), ((int)chckRange(desired_channels, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln_(233, "read.nim");
	{
		tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* e;
		if (!(data == NIM_NIL)) goto LA3_;
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*) newObj((&NTI_nkDbPegaPPXcgyPJXzLmBg_), sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ));
		(*e).Sup.Sup.m_type = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
		nimln_(234, "read.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.message), failureReason_jGKpadXTf7KJCfBI03WXEg());
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(234, "read.nim");
		raiseException((Exception*)e, "STBIException");
	}
	LA3_: ;
	nimln_(237, "read.nim");
	(*x) = ((NI) (width));
	nimln_(238, "read.nim");
	(*y) = ((NI) (height));
	nimln_(239, "read.nim");
	(*channels_in_file) = ((NI) (components));
	pixelData = (tySequence_uFLLGQVsiasALrzzzvqnZw*)0;
	nimln_(243, "read.nim");
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_8 = mulInt((*x), (*y));
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_9 = mulInt((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_8), (*channels_in_file));
	pixelData = (tySequence_uFLLGQVsiasALrzzzvqnZw*) newSeq((&NTI_uFLLGQVsiasALrzzzvqnZw_), ((NI)chckRange((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_9), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(244, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(pixelData->Sup.len)) raiseIndexError();
	T5_ = (pixelData ? pixelData->Sup.len : 0);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&pixelData->data[((NI) 0)]))), ((void*) (data)), ((NI)chckRange(T5_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(247, "read.nim");
	stbi_image_free(((void*) (data)));
	nimln_(249, "read.nim");
	genericSeqAssign((&result), pixelData, (&NTI_uFLLGQVsiasALrzzzvqnZw_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tySequence_uFLLGQVsiasALrzzzvqnZw*, loadFromFile16_24Bp3s4ROGXwM0hgUpC4hg)(FILE* f, NI* x, NI* y, NI* channels_in_file, NI desired_channels) {
	tySequence_uFLLGQVsiasALrzzzvqnZw* result;
	int width;
	int height;
	int components;
	unsigned char* data;
	tySequence_uFLLGQVsiasALrzzzvqnZw* pixelData;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_10;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_11;
	NI T5_;
	nimfr_("loadFromFile16", "read.nim");
{	result = (tySequence_uFLLGQVsiasALrzzzvqnZw*)0;
	width = (int)0;
	height = (int)0;
	components = (int)0;
	nimln_(270, "read.nim");
	data = stbi_load_from_file(f, (&width), (&height), (&components), ((int)chckRange(desired_channels, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln_(273, "read.nim");
	{
		tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* e;
		if (!(data == NIM_NIL)) goto LA3_;
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*) newObj((&NTI_nkDbPegaPPXcgyPJXzLmBg_), sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ));
		(*e).Sup.Sup.m_type = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
		nimln_(274, "read.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.message), failureReason_jGKpadXTf7KJCfBI03WXEg());
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(274, "read.nim");
		raiseException((Exception*)e, "STBIException");
	}
	LA3_: ;
	nimln_(277, "read.nim");
	(*x) = ((NI) (width));
	nimln_(278, "read.nim");
	(*y) = ((NI) (height));
	nimln_(279, "read.nim");
	(*channels_in_file) = ((NI) (components));
	pixelData = (tySequence_uFLLGQVsiasALrzzzvqnZw*)0;
	nimln_(283, "read.nim");
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_10 = mulInt((*x), (*y));
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_11 = mulInt((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_10), (*channels_in_file));
	pixelData = (tySequence_uFLLGQVsiasALrzzzvqnZw*) newSeq((&NTI_uFLLGQVsiasALrzzzvqnZw_), ((NI)chckRange((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_11), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(284, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(pixelData->Sup.len)) raiseIndexError();
	T5_ = (pixelData ? pixelData->Sup.len : 0);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&pixelData->data[((NI) 0)]))), ((void*) (data)), ((NI)chckRange(T5_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(287, "read.nim");
	stbi_image_free(((void*) (data)));
	nimln_(289, "read.nim");
	genericSeqAssign((&result), pixelData, (&NTI_uFLLGQVsiasALrzzzvqnZw_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tySequence_uFLLGQVsiasALrzzzvqnZw*, load16FromMemory_qZOJzYOLYDveos6SERzbNQ)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer, NI* x, NI* y, NI* channels_in_file, NI desired_channels) {
	tySequence_uFLLGQVsiasALrzzzvqnZw* result;
	unsigned char* castedBuffer;
	int width;
	int height;
	int components;
	unsigned short* data;
	NI T1_;
	tySequence_uFLLGQVsiasALrzzzvqnZw* pixelData;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_12;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_13;
	NI T6_;
	nimfr_("load16FromMemory", "read.nim");
{	result = (tySequence_uFLLGQVsiasALrzzzvqnZw*)0;
	nimln_(304, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(buffer->Sup.len)) raiseIndexError();
	castedBuffer = ((unsigned char*) ((&buffer->data[((NI) 0)])));
	width = (int)0;
	height = (int)0;
	components = (int)0;
	nimln_(311, "read.nim");
	T1_ = (buffer ? buffer->Sup.len : 0);
	data = stbi_load_16_from_memory(castedBuffer, ((int)chckRange(T1_, ((int) (-2147483647 -1)), ((int) 2147483647))), (&width), (&height), (&components), ((int)chckRange(desired_channels, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln_(314, "read.nim");
	{
		tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* e;
		if (!(data == NIM_NIL)) goto LA4_;
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*) newObj((&NTI_nkDbPegaPPXcgyPJXzLmBg_), sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ));
		(*e).Sup.Sup.m_type = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
		nimln_(315, "read.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.message), failureReason_jGKpadXTf7KJCfBI03WXEg());
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(315, "read.nim");
		raiseException((Exception*)e, "STBIException");
	}
	LA4_: ;
	nimln_(318, "read.nim");
	(*x) = ((NI) (width));
	nimln_(319, "read.nim");
	(*y) = ((NI) (height));
	nimln_(320, "read.nim");
	(*channels_in_file) = ((NI) (components));
	pixelData = (tySequence_uFLLGQVsiasALrzzzvqnZw*)0;
	nimln_(324, "read.nim");
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_12 = mulInt((*x), (*y));
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_13 = mulInt((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_12), (*channels_in_file));
	pixelData = (tySequence_uFLLGQVsiasALrzzzvqnZw*) newSeq((&NTI_uFLLGQVsiasALrzzzvqnZw_), ((NI)chckRange((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_13), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(325, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(pixelData->Sup.len)) raiseIndexError();
	T6_ = (pixelData ? pixelData->Sup.len : 0);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&pixelData->data[((NI) 0)]))), ((void*) (data)), ((NI)chckRange(T6_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(328, "read.nim");
	stbi_image_free(((void*) (data)));
	nimln_(330, "read.nim");
	genericSeqAssign((&result), pixelData, (&NTI_uFLLGQVsiasALrzzzvqnZw_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_4Xyxy0Om14N6K1l5e9bUPSQ)(void* p, NI op) {
	tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* a;
	NI T1_;
	a = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)p;
	T1_ = (NI)0;
}

N_NIMCALL(tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*, loadF_y5tlrnRToj29aTOStIISTZQ)(NimStringDesc* filename, NI* x, NI* y, NI* channels_in_file, NI desired_channels) {
	tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* result;
	int width;
	int height;
	int components;
	float* data;
	tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* pixelData;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_14;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_15;
	NI T5_;
	nimfr_("loadF", "read.nim");
{	result = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)0;
	width = (int)0;
	height = (int)0;
	components = (int)0;
	nimln_(377, "read.nim");
	data = stbi_loadf(filename->data, (&width), (&height), (&components), ((int)chckRange(desired_channels, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln_(380, "read.nim");
	{
		tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* e;
		if (!(data == NIM_NIL)) goto LA3_;
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*) newObj((&NTI_nkDbPegaPPXcgyPJXzLmBg_), sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ));
		(*e).Sup.Sup.m_type = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
		nimln_(381, "read.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.message), failureReason_jGKpadXTf7KJCfBI03WXEg());
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(381, "read.nim");
		raiseException((Exception*)e, "STBIException");
	}
	LA3_: ;
	nimln_(384, "read.nim");
	(*x) = ((NI) (width));
	nimln_(385, "read.nim");
	(*y) = ((NI) (height));
	nimln_(386, "read.nim");
	(*channels_in_file) = ((NI) (components));
	pixelData = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)0;
	nimln_(390, "read.nim");
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_14 = mulInt((*x), (*y));
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_15 = mulInt((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_14), (*channels_in_file));
	pixelData = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*) newSeq((&NTI_4Xyxy0Om14N6K1l5e9bUPSQ_), ((NI)chckRange((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_15), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(391, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(pixelData->Sup.len)) raiseIndexError();
	T5_ = (pixelData ? pixelData->Sup.len : 0);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&pixelData->data[((NI) 0)]))), ((void*) (data)), ((NI)chckRange(T5_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(394, "read.nim");
	stbi_image_free(((void*) (data)));
	nimln_(396, "read.nim");
	genericSeqAssign((&result), pixelData, (&NTI_4Xyxy0Om14N6K1l5e9bUPSQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*, loadFFromMemory_SNNFUvHzPQ65cEa8VGkWCg)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer, NI* x, NI* y, NI* channels_in_file, NI desired_channels) {
	tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* result;
	unsigned char* castedBuffer;
	int width;
	int height;
	int components;
	float* data;
	NI T1_;
	tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* pixelData;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_16;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_17;
	NI T6_;
	nimfr_("loadFFromMemory", "read.nim");
{	result = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)0;
	nimln_(409, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(buffer->Sup.len)) raiseIndexError();
	castedBuffer = ((unsigned char*) ((&buffer->data[((NI) 0)])));
	width = (int)0;
	height = (int)0;
	components = (int)0;
	nimln_(417, "read.nim");
	T1_ = (buffer ? buffer->Sup.len : 0);
	data = stbi_loadf_from_memory(castedBuffer, ((int)chckRange(T1_, ((int) (-2147483647 -1)), ((int) 2147483647))), (&width), (&height), (&components), ((int)chckRange(desired_channels, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln_(420, "read.nim");
	{
		tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* e;
		if (!(data == NIM_NIL)) goto LA4_;
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*) newObj((&NTI_nkDbPegaPPXcgyPJXzLmBg_), sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ));
		(*e).Sup.Sup.m_type = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
		nimln_(421, "read.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.message), failureReason_jGKpadXTf7KJCfBI03WXEg());
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(421, "read.nim");
		raiseException((Exception*)e, "STBIException");
	}
	LA4_: ;
	nimln_(424, "read.nim");
	(*x) = ((NI) (width));
	nimln_(425, "read.nim");
	(*y) = ((NI) (height));
	nimln_(426, "read.nim");
	(*channels_in_file) = ((NI) (components));
	pixelData = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)0;
	nimln_(430, "read.nim");
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_16 = mulInt((*x), (*y));
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_17 = mulInt((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_16), (*channels_in_file));
	pixelData = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*) newSeq((&NTI_4Xyxy0Om14N6K1l5e9bUPSQ_), ((NI)chckRange((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_17), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(431, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(pixelData->Sup.len)) raiseIndexError();
	T6_ = (pixelData ? pixelData->Sup.len : 0);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&pixelData->data[((NI) 0)]))), ((void*) (data)), ((NI)chckRange(T6_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(434, "read.nim");
	stbi_image_free(((void*) (data)));
	nimln_(436, "read.nim");
	genericSeqAssign((&result), pixelData, (&NTI_4Xyxy0Om14N6K1l5e9bUPSQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*, loadFFromFile_34hrADNf1JOeF51H4MjPVg)(FILE* f, NI* x, NI* y, NI* channels_in_file, NI desired_channels) {
	tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* result;
	int width;
	int height;
	int components;
	float* data;
	tySequence_4Xyxy0Om14N6K1l5e9bUPSQ* pixelData;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_18;
	NI TM_uWdNbvaeR1PPl0MvT9cIOIQ_19;
	NI T5_;
	nimfr_("loadFFromFile", "read.nim");
{	result = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)0;
	width = (int)0;
	height = (int)0;
	components = (int)0;
	nimln_(454, "read.nim");
	data = stbi_loadf_from_file(f, (&width), (&height), (&components), ((int)chckRange(desired_channels, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln_(457, "read.nim");
	{
		tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ* e;
		if (!(data == NIM_NIL)) goto LA3_;
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*) newObj((&NTI_nkDbPegaPPXcgyPJXzLmBg_), sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ));
		(*e).Sup.Sup.m_type = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
		nimln_(458, "read.nim");
		asgnRefNoCycle((void**) (&(*e).Sup.message), failureReason_jGKpadXTf7KJCfBI03WXEg());
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(458, "read.nim");
		raiseException((Exception*)e, "STBIException");
	}
	LA3_: ;
	nimln_(461, "read.nim");
	(*x) = ((NI) (width));
	nimln_(462, "read.nim");
	(*y) = ((NI) (height));
	nimln_(463, "read.nim");
	(*channels_in_file) = ((NI) (components));
	pixelData = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*)0;
	nimln_(467, "read.nim");
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_18 = mulInt((*x), (*y));
	TM_uWdNbvaeR1PPl0MvT9cIOIQ_19 = mulInt((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_18), (*channels_in_file));
	pixelData = (tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*) newSeq((&NTI_4Xyxy0Om14N6K1l5e9bUPSQ_), ((NI)chckRange((NI)(TM_uWdNbvaeR1PPl0MvT9cIOIQ_19), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(468, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(pixelData->Sup.len)) raiseIndexError();
	T5_ = (pixelData ? pixelData->Sup.len : 0);
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&pixelData->data[((NI) 0)]))), ((void*) (data)), ((NI)chckRange(T5_, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(471, "read.nim");
	stbi_image_free(((void*) (data)));
	nimln_(473, "read.nim");
	genericSeqAssign((&result), pixelData, (&NTI_4Xyxy0Om14N6K1l5e9bUPSQ_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, HDRToLDRGamma_Lsh39b9bxIV9a1rJgMKoM8fTA)(NF gamma) {
	nimfr_("HDRToLDRGamma", "read.nim");
	nimln_(508, "read.nim");
	stbi_hdr_to_ldr_gamma(((float) (gamma)));
	popFrame();
}

N_NIMCALL(void, HDRToLDRScale_x36tyiHIpnQez4k8tcOfug)(NF scale) {
	nimfr_("HDRToLDRScale", "read.nim");
	nimln_(513, "read.nim");
	stbi_hdr_to_ldr_scale(((float) (scale)));
	popFrame();
}

N_NIMCALL(void, LDRToHDRGamma_Lsh39b9bxIV9a1rJgMKoM8fTA_2)(NF gamma) {
	nimfr_("LDRToHDRGamma", "read.nim");
	nimln_(518, "read.nim");
	stbi_ldr_to_hdr_gamma(((float) (gamma)));
	popFrame();
}

N_NIMCALL(void, LDRToHDRScale_x36tyiHIpnQez4k8tcOfug_2)(NF scale) {
	nimfr_("LDRToHDRScale", "read.nim");
	nimln_(523, "read.nim");
	stbi_ldr_to_hdr_scale(((float) (scale)));
	popFrame();
}

N_NIMCALL(NIM_BOOL, isHDRFromMemory_mzZeUpW0Sh5x9cxIb9crdrog)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer) {
	NIM_BOOL result;
	unsigned char* castedBuffer;
	NI T1_;
	int T2_;
	nimfr_("isHDRFromMemory", "read.nim");
{	result = (NIM_BOOL)0;
	nimln_(528, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(buffer->Sup.len)) raiseIndexError();
	castedBuffer = ((unsigned char*) ((&buffer->data[((NI) 0)])));
	nimln_(529, "read.nim");
	T1_ = (buffer ? buffer->Sup.len : 0);
	T2_ = (int)0;
	T2_ = stbi_is_hdr_from_memory(castedBuffer, ((int)chckRange(T1_, ((int) (-2147483647 -1)), ((int) 2147483647))));
	result = (T2_ == ((NI32) 1));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isHDR_ZQioKayM35gE9b9bVR9auSaWw)(NimStringDesc* filename) {
	NIM_BOOL result;
	int T1_;
	nimfr_("isHDR", "read.nim");
{	result = (NIM_BOOL)0;
	nimln_(534, "read.nim");
	T1_ = (int)0;
	T1_ = stbi_is_hdr(filename->data);
	result = (T1_ == ((NI32) 1));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isHDRFromFile_Ea70oRc5oVycZj7ta4wzwQ)(FILE* f) {
	NIM_BOOL result;
	int T1_;
	nimfr_("isHDRFromFile", "read.nim");
{	result = (NIM_BOOL)0;
	nimln_(539, "read.nim");
	T1_ = (int)0;
	T1_ = stbi_is_hdr_from_file(f);
	result = (T1_ == ((NI32) 1));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, infoFromMemory_u8l9b9c8SKg4gdKhVXKVP9blw)(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ* buffer, NI* x, NI* y, NI* comp) {
	NIM_BOOL result;
	unsigned char* castedBuffer;
	int width;
	int height;
	int channels;
	int r;
	NI T1_;
	nimfr_("infoFromMemory", "read.nim");
{	result = (NIM_BOOL)0;
	nimln_(575, "read.nim");
	if ((NU)(((NI) 0)) >= (NU)(buffer->Sup.len)) raiseIndexError();
	castedBuffer = ((unsigned char*) ((&buffer->data[((NI) 0)])));
	width = (int)0;
	height = (int)0;
	channels = (int)0;
	nimln_(579, "read.nim");
	T1_ = (buffer ? buffer->Sup.len : 0);
	r = stbi_info_from_memory(castedBuffer, ((int)chckRange(T1_, ((int) (-2147483647 -1)), ((int) 2147483647))), (&width), (&height), (&channels));
	nimln_(582, "read.nim");
	(*x) = ((NI) (width));
	nimln_(583, "read.nim");
	(*y) = ((NI) (height));
	nimln_(584, "read.nim");
	(*comp) = ((NI) (channels));
	nimln_(585, "read.nim");
	result = (r == ((NI32) 1));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, info_VjXaJL7e9cMuRxP64g4KgaQ)(NimStringDesc* filename, NI* x, NI* y, NI* comp) {
	NIM_BOOL result;
	int width;
	int height;
	int channels;
	int r;
	nimfr_("info", "read.nim");
{	result = (NIM_BOOL)0;
	width = (int)0;
	height = (int)0;
	channels = (int)0;
	nimln_(595, "read.nim");
	r = stbi_info(filename->data, (&width), (&height), (&channels));
	nimln_(598, "read.nim");
	(*x) = ((NI) (width));
	nimln_(599, "read.nim");
	(*y) = ((NI) (height));
	nimln_(600, "read.nim");
	(*comp) = ((NI) (channels));
	nimln_(601, "read.nim");
	result = (r == ((NI32) 1));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, infoFromFile_UGn9aG9bLDjdc7nonQQPq9b6Q)(FILE* f, NI* x, NI* y, NI* comp) {
	NIM_BOOL result;
	int width;
	int height;
	int channels;
	int r;
	nimfr_("infoFromFile", "read.nim");
{	result = (NIM_BOOL)0;
	width = (int)0;
	height = (int)0;
	channels = (int)0;
	nimln_(613, "read.nim");
	r = stbi_info_from_file(f, (&width), (&height), (&channels));
	nimln_(616, "read.nim");
	(*x) = ((NI) (width));
	nimln_(617, "read.nim");
	(*y) = ((NI) (height));
	nimln_(618, "read.nim");
	(*comp) = ((NI) (channels));
	nimln_(619, "read.nim");
	result = (r == ((NI32) 1));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, setUnpremultiplyOnLoad_n7srZhNnr2VA69cDLKfieow)(NIM_BOOL unpremultiply) {
	NI T1_;
	nimfr_("setUnpremultiplyOnLoad", "read.nim");
	nimln_(643, "read.nim");
	T1_ = (NI)0;
	{
		if (!unpremultiply) goto LA4_;
		T1_ = ((NI) 1);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) 0);
	}
	LA2_: ;
	stbi_set_unpremultiply_on_load(((int)chckRange(T1_, ((int) (-2147483647 -1)), ((int) 2147483647))));
	popFrame();
}

N_NIMCALL(void, convertIPhonePNGToRGB_689aweJ9cfBKRoqe4WZmyR7A)(NIM_BOOL convert) {
	NI T1_;
	nimfr_("convertIPhonePNGToRGB", "read.nim");
	nimln_(650, "read.nim");
	T1_ = (NI)0;
	{
		if (!convert) goto LA4_;
		T1_ = ((NI) 1);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) 0);
	}
	LA2_: ;
	stbi_convert_iphone_png_to_rgb(((int)chckRange(T1_, ((int) (-2147483647 -1)), ((int) 2147483647))));
	popFrame();
}

N_NIMCALL(void, setFlipVerticallyOnLoad_ayevlb02tzQDH45TRoMJUg)(NIM_BOOL flip) {
	NI T1_;
	nimfr_("setFlipVerticallyOnLoad", "read.nim");
	nimln_(657, "read.nim");
	T1_ = (NI)0;
	{
		if (!flip) goto LA4_;
		T1_ = ((NI) 1);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) 0);
	}
	LA2_: ;
	stbi_set_flip_vertically_on_load(((int)chckRange(T1_, ((int) (-2147483647 -1)), ((int) 2147483647))));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stb_image_readInit000)(void) {
	nimfr_("read", "read.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stb_image_readDatInit000)(void) {
static TNimNode TM_uWdNbvaeR1PPl0MvT9cIOIQ_0[1];
NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_.size = sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ);
NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_.kind = 17;
NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_uWdNbvaeR1PPl0MvT9cIOIQ_0[0].len = 0; TM_uWdNbvaeR1PPl0MvT9cIOIQ_0[0].kind = 2;
NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_.node = &TM_uWdNbvaeR1PPl0MvT9cIOIQ_0[0];
NTI_nkDbPegaPPXcgyPJXzLmBg_.size = sizeof(tyObject_STBIException_1qE9c5Z00HW9cNKb1tJNxkhQ*);
NTI_nkDbPegaPPXcgyPJXzLmBg_.kind = 22;
NTI_nkDbPegaPPXcgyPJXzLmBg_.base = (&NTI_1qE9c5Z00HW9cNKb1tJNxkhQ_);
NTI_nkDbPegaPPXcgyPJXzLmBg_.marker = Marker_tyRef_nkDbPegaPPXcgyPJXzLmBg;
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.size = sizeof(tySequence_6H5Oh5UUvVCLiakt9aTwtUQ*);
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.kind = 24;
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.base = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.flags = 2;
NTI_6H5Oh5UUvVCLiakt9aTwtUQ_.marker = Marker_tySequence_6H5Oh5UUvVCLiakt9aTwtUQ;
NTI_uFLLGQVsiasALrzzzvqnZw_.size = sizeof(tySequence_uFLLGQVsiasALrzzzvqnZw*);
NTI_uFLLGQVsiasALrzzzvqnZw_.kind = 24;
NTI_uFLLGQVsiasALrzzzvqnZw_.base = (&NTI_M4na42GvebBMnI5wV9cYMxg_);
NTI_uFLLGQVsiasALrzzzvqnZw_.flags = 2;
NTI_uFLLGQVsiasALrzzzvqnZw_.marker = Marker_tySequence_uFLLGQVsiasALrzzzvqnZw;
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.size = sizeof(tySequence_4Xyxy0Om14N6K1l5e9bUPSQ*);
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.kind = 24;
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.base = (&NTI_C875xFvYpI7aGybrDGHIaQ_);
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.flags = 2;
NTI_4Xyxy0Om14N6K1l5e9bUPSQ_.marker = Marker_tySequence_4Xyxy0Om14N6K1l5e9bUPSQ;
}

