/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields  -IC:\nim\lib -o C:\projects\easygl\examples\nimcache\stdlib_basic2d.o C:\projects\easygl\examples\nimcache\stdlib_basic2d.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg;
typedef struct tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug;
typedef struct tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA;
typedef struct tyObject_ArithmeticError_QcJsjWXxMFpjHfkCIK5ExA tyObject_ArithmeticError_QcJsjWXxMFpjHfkCIK5ExA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg {
NF ax;
NF ay;
NF bx;
NF by;
NF tx;
NF ty;
};
struct tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug {
NF x;
NF y;
};
struct tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA {
NF x;
NF y;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_ArithmeticError_QcJsjWXxMFpjHfkCIK5ExA {
  Exception Sup;
};
struct tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA {
  tyObject_ArithmeticError_QcJsjWXxMFpjHfkCIK5ExA Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_NIMCALL(NimStringDesc*, rtos_3imJPLy7In9aRjL9c9aiFr9c3g)(NF val);
N_NIMCALL(NimStringDesc*, nsuformatFloat)(NF f, tyEnum_FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ format, NI precision, NIM_CHAR decimalSep);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, clamp_BGhQiHv5LFkg9aDgeidEq0g)(NF x, NF a, NF b);
N_NIMCALL(NF, safeArccos_3uSopz0panQtDF7zUu7C9aA)(NF v);
static N_INLINE(void, setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t, NF ax, NF ay, NF bx, NF by, NF tx, NF ty);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, matrix2d_ZkrhJTvT5qdZLXWIJxuuVw)(NF ax, NF ay, NF bx, NF by, NF tx, NF ty);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, amp__Fk9aisAzRUXLYKBwoslulJw)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* a, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* b);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, scale_2sQpCBH2qOWI6qBqmko77Q)(NF s);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, scale_D2JCT3Z9cROYzaVaC8EDd2A)(NF s, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, stretch_9b77Usp62PE9bAibdbfmZvdg)(NF sx, NF sy);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, stretch_9bflUjF6MyqXKVmDE2dGwGg)(NF sx, NF sy, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, move_g3yJo9bjO09bfl6mXcLv9cqhg)(NF dx, NF dy);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, move_duMa8Golajnh9a16vrdL7Cw)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, rotate_ujhF31Ew1H7QWys6JKWZFg)(NF rad);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, rotate_3y1rGWCyfjw9cCEaAN4Xyrg)(NF rad, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, mirror_6UCZlNzQuk9bpm9b8yTUbsyQ)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, mirror_3MueEwcSSPkUJZW86La7MQ)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, skew_v6Les9bRdQES4A5jgcaugPQ)(NF xskew, NF yskew);
N_NIMCALL(NimStringDesc*, dollar__dGX9bjsjLl3CXKQdaYwqgHA)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NIM_BOOL, isUniform_S811YFJ0DkOH0UGTSbpNPQ)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t, NF tol);
N_NIMCALL(NF, determinant_qbdsEeWv1HhmDNAQvcsJyw)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t);
N_NIMCALL(NIM_BOOL, isMirroring_f5k9c6DGdlUF6hh69cd0nQtQ)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m);
N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, inverse_AEToUYBg9c1L8h309a3noQZA)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, equals_B9a9bihKp19czsKgM7E4DwQLw)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m1, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m2, NF tol);
N_NIMCALL(NIM_BOOL, eqtilde__ounRcA0VwHoq8l1TZM6OQg)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m1, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m2);
N_NIMCALL(NIM_BOOL, isIdentity_EmcS4cUhJ6G9ceMvF0sMJ4A)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m, NF tol);
N_NIMCALL(void, apply_f06CKgVkHkCPrp69c1VkNTw)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m, NF* x, NF* y, NIM_BOOL translate);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d)(NF x, NF y);
N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, polarVector2d_2K5U8o4UaLz89akm1AvvS6A)(NF ang, NF len);
N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, slopeVector2d_2417hh0F6xyDekjIlOe21A)(NF slope, NF len);
static N_INLINE(NF, len_MpSCgcxEZtYWTBuEMJUaIgbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
N_NIMCALL(void, leneq__d7vvQbGwGw9aDTglUln0OPg)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, NF newlen);
static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x, NF y);
static N_INLINE(NF, sqrLen_MpSCgcxEZtYWTBuEMJUaIg_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
N_NIMCALL(NF, angle_jpx9aVKvbHuECXQ3uv5sdGA)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y);
N_NIMCALL(NimStringDesc*, dollar__KNZuzaUJrmopxmNu9aZOB9bA)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, amp__H2WQIQQ2D7pJCqSLsOLCxQ)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m);
static N_INLINE(void, ampeq__b7en8I9a5jBX5TdB9cEdlKuwbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m);
N_NIMCALL(NIM_BOOL, tryNormalize_BqsLwyP1Q2mmowpWiNwdzw)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v);
static N_INLINE(void, slasheq__7kHiltrvRlcg6wSYR3CxAwsystem)(NF* x, NF y);
static N_INLINE(void, normalize_D082ouE4v9aynDe1fZCQY0Qbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v);
N_NIMCALL(void, transformNorm_eCblPLXj9bpzHBxKqDFVHSQ)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t);
N_NIMCALL(void, transformInv_eCblPLXj9bpzHBxKqDFVHSQ_2)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t);
N_NIMCALL(void, transformNormInv_eCblPLXj9bpzHBxKqDFVHSQ_3)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t);
static N_INLINE(void, rotate90_D082ouE4v9aynDe1fZCQY0Q_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v);
static N_INLINE(void, rotate180_D082ouE4v9aynDe1fZCQY0Q_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v);
static N_INLINE(void, rotate270_D082ouE4v9aynDe1fZCQY0Q_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v);
N_NIMCALL(void, rotate_NNq9cyE9a9aA9bP29bAGLZEPkeA)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, NF rad);
static N_INLINE(void, scale_8I9c8xBfd3ZYUR4t5su9aiEAbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, NF fac);
static N_INLINE(void, stretch_qiBYYSjb6dcXtdMjL5g4bAbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, NF facx, NF facy);
N_NIMCALL(void, mirror_kLaFeSdfrShnu03l7Gei0g)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA mirrvec);
N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__8A0se4zNNtldWGqC9aM5sgw)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, plus__N47oJl3jYu7DD4h0uckZNAbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, plus__tGCcuKwuFv3czilpjeV5TAbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, NF b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, plus__vh9ayTY2e7ACJx9a0rD3b0Jgbasic2d)(NF a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__N47oJl3jYu7DD4h0uckZNA_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__tGCcuKwuFv3czilpjeV5TA_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, NF b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__vh9ayTY2e7ACJx9a0rD3b0Jg_2basic2d)(NF a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, star__N47oJl3jYu7DD4h0uckZNA_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, star__tGCcuKwuFv3czilpjeV5TA_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, NF b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, star__vh9ayTY2e7ACJx9a0rD3b0Jg_3basic2d)(NF a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, slash__N47oJl3jYu7DD4h0uckZNA_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, slash__tGCcuKwuFv3czilpjeV5TA_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, NF b);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, slash__vh9ayTY2e7ACJx9a0rD3b0Jg_4basic2d)(NF a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(void, pluseq__jxViqne0KjwGpG3r4qzcWQbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(void, pluseq__rWWFNP2c6vvhU6RKFR7VXwbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, NF b);
static N_INLINE(void, minuseq__jxViqne0KjwGpG3r4qzcWQ_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwtimes)(NF* x, NF y);
static N_INLINE(void, minuseq__rWWFNP2c6vvhU6RKFR7VXw_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, NF b);
static N_INLINE(void, stareq__jxViqne0KjwGpG3r4qzcWQ_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(void, stareq__rWWFNP2c6vvhU6RKFR7VXw_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, NF b);
static N_INLINE(void, slasheq__jxViqne0KjwGpG3r4qzcWQ_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b);
static N_INLINE(void, slasheq__rWWFNP2c6vvhU6RKFR7VXw_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, NF b);
N_NIMCALL(NF, dot_UMotgrIsXNHj9b9cjNtuOxcA)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2);
N_NIMCALL(NF, cross_UMotgrIsXNHj9b9cjNtuOxcA_2)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2);
N_NIMCALL(NIM_BOOL, equals_YlkCr9aLbK8cRfctU27mT0g)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2, NF tol);
N_NIMCALL(NIM_BOOL, eqtilde__YiLpvs3yoG4GgNef1O8Q0Q)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2);
N_NIMCALL(NF, angleTo_UMotgrIsXNHj9b9cjNtuOxcA_3)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2);
N_NIMCALL(NF, angleCCW_UMotgrIsXNHj9b9cjNtuOxcA_4)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2);
N_NIMCALL(NF, angleCW_UMotgrIsXNHj9b9cjNtuOxcA_5)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2);
N_NIMCALL(NF, turnAngle_UMotgrIsXNHj9b9cjNtuOxcA_6)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2);
N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, bisect_BkRBc2VZG9as1tDSyv9bgZYQ)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2);
static N_INLINE(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, point2d_4HtTb6DBuFYILwb7lqld9agbasic2d)(NF x, NF y);
N_NIMCALL(NF, sqrDist_inohp9bGa7FVYBb9biOHHX4g)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b);
static N_INLINE(NF, dist_8eiFVGqElBlsuJ69apJn34Qbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b);
N_NIMCALL(NF, angle_inohp9bGa7FVYBb9biOHHX4g_2)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b);
N_NIMCALL(NimStringDesc*, dollar__4EQ4uWvU5Cm07oTXBQtD7Q)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p);
static N_INLINE(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, amp__PI6cZrDDf2SDzREFmRVFywbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t);
static N_INLINE(void, ampeq__Mcrst0GjTEBJbss0HgUdnAbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t);
static N_INLINE(void, transformInv_Mcrst0GjTEBJbss0HgUdnA_2basic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t);
static N_INLINE(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, plus__q81dFZGTLUb4p1FMszt1zAbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
static N_INLINE(void, pluseq__FhMmgV9c9csOjbyaRVR6fA3wbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
static N_INLINE(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, minus__q81dFZGTLUb4p1FMszt1zA_2basic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__K59coQjPs7Tllh50beRwK1Abasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p1, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p2);
static N_INLINE(void, minuseq__FhMmgV9c9csOjbyaRVR6fA3w_2basic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
static N_INLINE(NIM_BOOL, equals_G7pjBf3BhCkaFjfbrpRp5Abasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p1, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p2, NF tol);
static N_INLINE(NIM_BOOL, eqtilde__l72v28qwjjOADB5JC9adeDwbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p1, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p2);
N_NIMCALL(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, polar_R1XspyRFM0GHMX3bpfn6oQ)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, NF ang, NF dist);
N_NIMCALL(void, rotate_TmBpU7PM0PUMdVzew9ao9cBg)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF rad);
N_NIMCALL(void, rotate_RPykYWgbcjdNOc9bHPQTgZQ)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF rad, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org);
static N_INLINE(void, scale_PA4uX2ATo70xFXHtdtKw0wbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF fac);
static N_INLINE(void, scale_rlg9cR5LaB6M0z6QOTP0e6wbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF fac, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org);
static N_INLINE(void, stretch_TBlDxsuzdpvxCd0fecb21Abasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF facx, NF facy);
static N_INLINE(void, stretch_vwKutqxWzKGeCuLFZUw9a7wbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF facx, NF facy, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org);
static N_INLINE(void, move_DwI9cSc9ce7A3ZXsjGyqZjWQbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF dx, NF dy);
static N_INLINE(void, move_FhMmgV9c9csOjbyaRVR6fA3w_3basic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v);
N_NIMCALL(NF, sgnArea_kFyWnP1SkVxW8qpnjM9aWKA)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug c);
N_NIMCALL(NF, area_kFyWnP1SkVxW8qpnjM9aWKA_2)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug c);
N_NIMCALL(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, closestPoint_JIOsw8Im7T8GxzdK9ame5bA)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* pts, NI ptsLen_0);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NF, mod_sGqENdekUaHyJla6nH3ncQ)(NF x, NF y);
N_NIMCALL(NF, normAngle_P8e2c9aikm3VRG6gsXpFpIA)(NF ang);
static N_INLINE(NF, degToRad_6PAXAFwfQC69aYEj2QnQRxwbasic2d)(NF deg);
static N_INLINE(NF, radToDeg_XBsJzgPXkAYChZQhqMAzsgbasic2d)(NF rad);
tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg IDMATRIX_DQf5P8YCykuDxNmZ5bvG7g;
tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug ORIGO_fcPFYT9cYuzJZVhuTlBCWIA;
tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA XAXIS_cHisHYvnFnWkQFsXQwR8LA;
tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA YAXIS_Tg25xvoRc1btSr7LczyLoQ;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_BdGSl5vgXXoo8kaIdXXVyw_;
extern TNimType NTI_p6OJ2WGp1zYZkMyhPlJPZA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_uZDJJp1iqREI0Whfe9c2S0w_2, ",", 1);
STRING_LITERAL(TM_uZDJJp1iqREI0Whfe9c2S0w_3, "Cannot invert a zero determinant matrix", 39);
STRING_LITERAL(TM_uZDJJp1iqREI0Whfe9c2S0w_4, "Cannot normalize zero length vector", 35);
STRING_LITERAL(TM_uZDJJp1iqREI0Whfe9c2S0w_5, "Matrix is not invertible", 24);
STRING_LITERAL(TM_uZDJJp1iqREI0Whfe9c2S0w_6, "\015\012  0 < len(pts) ", 17);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NimStringDesc*, rtos_3imJPLy7In9aRjL9c9aiFr9c3g)(NF val) {
	NimStringDesc* result;
	nimfr_("rtos", "basic2d.nim");
{	result = (NimStringDesc*)0;
	nimln_(110, "basic2d.nim");
	result = nsuformatFloat(val, ((tyEnum_FloatFormatMode_pNvEoaqwoxKyoASD11vSgQ) 0), ((NI) 0), 46);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, safeArccos_3uSopz0panQtDF7zUu7C9aA)(NF v) {
	NF result;
	NF T1_;
	nimfr_("safeArccos", "basic2d.nim");
{	result = (NF)0;
	nimln_(116, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = clamp_BGhQiHv5LFkg9aDgeidEq0g(v, -1.0000000000000000e+000, 1.0000000000000000e+000);
	result = acos(T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t, NF ax, NF ay, NF bx, NF by, NF tx, NF ty) {
	nimfr_("setElements", "basic2d.nim");
	nimln_(137, "basic2d.nim");
	(*t).ax = ax;
	nimln_(138, "basic2d.nim");
	(*t).ay = ay;
	nimln_(139, "basic2d.nim");
	(*t).bx = bx;
	nimln_(140, "basic2d.nim");
	(*t).by = by;
	nimln_(141, "basic2d.nim");
	(*t).tx = tx;
	nimln_(142, "basic2d.nim");
	(*t).ty = ty;
	popFrame();
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, matrix2d_ZkrhJTvT5qdZLXWIJxuuVw)(NF ax, NF ay, NF bx, NF by, NF tx, NF ty) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	nimfr_("matrix2d", "basic2d.nim");
	nimln_(145, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), ax, ay, bx, by, tx, ty);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, amp__Fk9aisAzRUXLYKBwoslulJw)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* a, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* b) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	nimfr_("&", "basic2d.nim");
	nimln_(153, "basic2d.nim");
	nimln_(154, "basic2d.nim");
	nimln_(155, "basic2d.nim");
	nimln_(156, "basic2d.nim");
	nimln_(157, "basic2d.nim");
	nimln_(158, "basic2d.nim");
	nimln_(159, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), ((NF)(((NF)((*a).ax) * (NF)((*b).ax))) + (NF)(((NF)((*a).ay) * (NF)((*b).bx)))), ((NF)(((NF)((*a).ax) * (NF)((*b).ay))) + (NF)(((NF)((*a).ay) * (NF)((*b).by)))), ((NF)(((NF)((*a).bx) * (NF)((*b).ax))) + (NF)(((NF)((*a).by) * (NF)((*b).bx)))), ((NF)(((NF)((*a).bx) * (NF)((*b).ay))) + (NF)(((NF)((*a).by) * (NF)((*b).by)))), ((NF)(((NF)(((NF)((*a).tx) * (NF)((*b).ax))) + (NF)(((NF)((*a).ty) * (NF)((*b).bx))))) + (NF)((*b).tx)), ((NF)(((NF)(((NF)((*a).tx) * (NF)((*b).ay))) + (NF)(((NF)((*a).ty) * (NF)((*b).by))))) + (NF)((*b).ty)));
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, scale_2sQpCBH2qOWI6qBqmko77Q)(NF s) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	nimfr_("scale", "basic2d.nim");
	nimln_(164, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), s, 0.0, 0.0, s, 0.0, 0.0);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, scale_D2JCT3Z9cROYzaVaC8EDd2A)(NF s, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	nimfr_("scale", "basic2d.nim");
	nimln_(168, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), s, 0.0, 0.0, s, ((NF)(org.x) - (NF)(((NF)(s) * (NF)(org.x)))), ((NF)(org.y) - (NF)(((NF)(s) * (NF)(org.y)))));
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, stretch_9b77Usp62PE9bAibdbfmZvdg)(NF sx, NF sy) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	nimfr_("stretch", "basic2d.nim");
	nimln_(173, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), sx, 0.0, 0.0, sy, 0.0, 0.0);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, stretch_9bflUjF6MyqXKVmDE2dGwGg)(NF sx, NF sy, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	nimfr_("stretch", "basic2d.nim");
	nimln_(179, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), sx, 0.0, 0.0, sy, ((NF)(org.x) - (NF)(((NF)(sx) * (NF)(org.x)))), ((NF)(org.y) - (NF)(((NF)(sy) * (NF)(org.y)))));
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, move_g3yJo9bjO09bfl6mXcLv9cqhg)(NF dx, NF dy) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	nimfr_("move", "basic2d.nim");
	nimln_(183, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), 1.0000000000000000e+000, 0.0, 0.0, 1.0000000000000000e+000, dx, dy);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, move_duMa8Golajnh9a16vrdL7Cw)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	nimfr_("move", "basic2d.nim");
	nimln_(187, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), 1.0000000000000000e+000, 0.0, 0.0, 1.0000000000000000e+000, v.x, v.y);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, rotate_ujhF31Ew1H7QWys6JKWZFg)(NF rad) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	NF s;
	NF c;
	nimfr_("rotate", "basic2d.nim");
	nimln_(193, "basic2d.nim");
	s = sin(rad);
	nimln_(194, "basic2d.nim");
	c = cos(rad);
	nimln_(195, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), c, s, -(s), c, 0.0, 0.0);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, rotate_3y1rGWCyfjw9cCEaAN4Xyrg)(NF rad, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	NF s;
	NF c;
	nimfr_("rotate", "basic2d.nim");
	nimln_(202, "basic2d.nim");
	s = sin(rad);
	nimln_(203, "basic2d.nim");
	c = cos(rad);
	nimln_(204, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), c, s, -(s), c, ((NF)(((NF)(org.x) + (NF)(((NF)(s) * (NF)(org.y))))) - (NF)(((NF)(c) * (NF)(org.x)))), ((NF)(((NF)(org.y) - (NF)(((NF)(c) * (NF)(org.y))))) - (NF)(((NF)(s) * (NF)(org.x)))));
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, mirror_6UCZlNzQuk9bpm9b8yTUbsyQ)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	NF sqx;
	NF sqy;
	NF nd;
	NF xy2;
	NF sqd;
	nimfr_("mirror", "basic2d.nim");
{	nimln_(211, "basic2d.nim");
	sqx = ((NF)(v.x) * (NF)(v.x));
	nimln_(212, "basic2d.nim");
	sqy = ((NF)(v.y) * (NF)(v.y));
	nimln_(213, "basic2d.nim");
	nd = ((NF)(1.0000000000000000e+000) / (NF)(((NF)(sqx) + (NF)(sqy))));
	nimln_(214, "basic2d.nim");
	xy2 = ((NF)(((NF)(((NF)(v.x) * (NF)(v.y))) * (NF)(2.0000000000000000e+000))) * (NF)(nd));
	nimln_(215, "basic2d.nim");
	sqd = ((NF)(nd) * (NF)(((NF)(sqx) - (NF)(sqy))));
	nimln_(217, "basic2d.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (nd == INF);
		if (T3_) goto LA4_;
		T3_ = (nd == -INF);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(218, "basic2d.nim");
		result = IDMATRIX_DQf5P8YCykuDxNmZ5bvG7g;
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(220, "basic2d.nim");
	nimln_(222, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), sqd, xy2, xy2, -(sqd), 0.0, 0.0);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, mirror_3MueEwcSSPkUJZW86La7MQ)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	NF sqx;
	NF sqy;
	NF nd;
	NF xy2;
	NF sqd;
	nimfr_("mirror", "basic2d.nim");
{	nimln_(230, "basic2d.nim");
	sqx = ((NF)(v.x) * (NF)(v.x));
	nimln_(231, "basic2d.nim");
	sqy = ((NF)(v.y) * (NF)(v.y));
	nimln_(232, "basic2d.nim");
	nd = ((NF)(1.0000000000000000e+000) / (NF)(((NF)(sqx) + (NF)(sqy))));
	nimln_(233, "basic2d.nim");
	xy2 = ((NF)(((NF)(((NF)(v.x) * (NF)(v.y))) * (NF)(2.0000000000000000e+000))) * (NF)(nd));
	nimln_(234, "basic2d.nim");
	sqd = ((NF)(nd) * (NF)(((NF)(sqx) - (NF)(sqy))));
	nimln_(236, "basic2d.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (nd == INF);
		if (T3_) goto LA4_;
		T3_ = (nd == -INF);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(237, "basic2d.nim");
		result = IDMATRIX_DQf5P8YCykuDxNmZ5bvG7g;
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(239, "basic2d.nim");
	nimln_(241, "basic2d.nim");
	nimln_(242, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), sqd, xy2, xy2, -(sqd), ((NF)(((NF)(org.x) - (NF)(((NF)(org.y) * (NF)(xy2))))) - (NF)(((NF)(org.x) * (NF)(sqd)))), ((NF)(((NF)(org.y) - (NF)(((NF)(org.x) * (NF)(xy2))))) + (NF)(((NF)(org.y) * (NF)(sqd)))));
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, skew_v6Les9bRdQES4A5jgcaugPQ)(NF xskew, NF yskew) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	NF T1_;
	NF T2_;
	NF T3_;
	NF T4_;
	nimfr_("skew", "basic2d.nim");
	nimln_(250, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = cos(yskew);
	T2_ = (NF)0;
	T2_ = sin(yskew);
	T3_ = (NF)0;
	T3_ = sin(xskew);
	T4_ = (NF)0;
	T4_ = cos(xskew);
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), T1_, T2_, -(T3_), T4_, 0.0, 0.0);
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, dollar__dGX9bjsjLl3CXKQdaYwqgHA)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	NimStringDesc* T5_;
	NimStringDesc* T6_;
	NimStringDesc* T7_;
	nimfr_("$", "basic2d.nim");
{	nimln_(255, "basic2d.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = rtos_3imJPLy7In9aRjL9c9aiFr9c3g((*t).ax);
	T3_ = (NimStringDesc*)0;
	T3_ = rtos_3imJPLy7In9aRjL9c9aiFr9c3g((*t).ay);
	nimln_(256, "basic2d.nim");
	T4_ = (NimStringDesc*)0;
	T4_ = rtos_3imJPLy7In9aRjL9c9aiFr9c3g((*t).bx);
	T5_ = (NimStringDesc*)0;
	T5_ = rtos_3imJPLy7In9aRjL9c9aiFr9c3g((*t).by);
	nimln_(257, "basic2d.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = rtos_3imJPLy7In9aRjL9c9aiFr9c3g((*t).tx);
	T7_ = (NimStringDesc*)0;
	T7_ = rtos_3imJPLy7In9aRjL9c9aiFr9c3g((*t).ty);
	T1_ = rawNewString(T2_->Sup.len + T3_->Sup.len + T4_->Sup.len + T5_->Sup.len + T6_->Sup.len + T7_->Sup.len + 5);
appendString(T1_, T2_);
appendString(T1_, ((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_2));
appendString(T1_, T3_);
appendString(T1_, ((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_2));
appendString(T1_, T4_);
appendString(T1_, ((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_2));
appendString(T1_, T5_);
appendString(T1_, ((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_2));
appendString(T1_, T6_);
appendString(T1_, ((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_2));
appendString(T1_, T7_);
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isUniform_S811YFJ0DkOH0UGTSbpNPQ)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t, NF tol) {
	NIM_BOOL result;
	nimfr_("isUniform", "basic2d.nim");
{	result = (NIM_BOOL)0;
	nimln_(267, "basic2d.nim");
	{
		if (!((((NF)(((NF)((*t).ax) * (NF)((*t).bx))) + (NF)(((NF)((*t).ay) * (NF)((*t).by)))) < 0? -(((NF)(((NF)((*t).ax) * (NF)((*t).bx))) + (NF)(((NF)((*t).ay) * (NF)((*t).by))))) : (((NF)(((NF)((*t).ax) * (NF)((*t).bx))) + (NF)(((NF)((*t).ay) * (NF)((*t).by)))))) <= tol)) goto LA3_;
		nimln_(269, "basic2d.nim");
		{
			if (!((((NF)(((NF)(((NF)((*t).ax) * (NF)((*t).ax))) + (NF)(((NF)((*t).ay) * (NF)((*t).ay))))) - (NF)(((NF)(((NF)((*t).bx) * (NF)((*t).bx))) + (NF)(((NF)((*t).by) * (NF)((*t).by)))))) < 0? -(((NF)(((NF)(((NF)((*t).ax) * (NF)((*t).ax))) + (NF)(((NF)((*t).ay) * (NF)((*t).ay))))) - (NF)(((NF)(((NF)((*t).bx) * (NF)((*t).bx))) + (NF)(((NF)((*t).by) * (NF)((*t).by))))))) : (((NF)(((NF)(((NF)((*t).ax) * (NF)((*t).ax))) + (NF)(((NF)((*t).ay) * (NF)((*t).ay))))) - (NF)(((NF)(((NF)((*t).bx) * (NF)((*t).bx))) + (NF)(((NF)((*t).by) * (NF)((*t).by)))))))) <= tol)) goto LA7_;
			nimln_(270, "basic2d.nim");
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
	}
	LA3_: ;
	nimln_(271, "basic2d.nim");
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, determinant_qbdsEeWv1HhmDNAQvcsJyw)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t) {
	NF result;
	nimfr_("determinant", "basic2d.nim");
{	result = (NF)0;
	nimln_(277, "basic2d.nim");
	result = ((NF)(((NF)((*t).ax) * (NF)((*t).by))) - (NF)(((NF)((*t).bx) * (NF)((*t).ay))));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isMirroring_f5k9c6DGdlUF6hh69cd0nQtQ)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m) {
	NIM_BOOL result;
	NF T1_;
	nimfr_("isMirroring", "basic2d.nim");
{	result = (NIM_BOOL)0;
	nimln_(282, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = determinant_qbdsEeWv1HhmDNAQvcsJyw(m);
	result = (T1_ < 0.0);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(255, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(257, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(258, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(196, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(223, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(224, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(269, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(378, "system.nim");
		nimln_(269, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(270, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(378, "system.nim");
		nimln_(270, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg, inverse_AEToUYBg9c1L8h309a3noQZA)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m) {
	tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg result;
	NF d;
	nimfr_("inverse", "basic2d.nim");
	nimln_(288, "basic2d.nim");
	d = determinant_qbdsEeWv1HhmDNAQvcsJyw(m);
	nimln_(289, "basic2d.nim");
	{
		tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA* e;
		NimStringDesc* T5_;
		if (!(d == 0.0)) goto LA3_;
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*) newObj((&NTI_BdGSl5vgXXoo8kaIdXXVyw_), sizeof(tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA));
		(*e).Sup.Sup.Sup.m_type = (&NTI_p6OJ2WGp1zYZkMyhPlJPZA_);
		nimln_(290, "basic2d.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_3));
		if (T5_) nimGCunrefNoCycle(T5_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(290, "basic2d.nim");
		raiseException((Exception*)e, "DivByZeroError");
	}
	LA3_: ;
	nimln_(292, "basic2d.nim");
	nimln_(293, "basic2d.nim");
	nimln_(294, "basic2d.nim");
	nimln_(295, "basic2d.nim");
	nimln_(296, "basic2d.nim");
	setElements_gxRGxiigkbTdeR9ar89bltjgbasic2d((&result), ((NF)((*m).by) / (NF)(d)), ((NF)(-((*m).ay)) / (NF)(d)), ((NF)(-((*m).bx)) / (NF)(d)), ((NF)((*m).ax) / (NF)(d)), ((NF)(((NF)(((NF)((*m).bx) * (NF)((*m).ty))) - (NF)(((NF)((*m).by) * (NF)((*m).tx))))) / (NF)(d)), ((NF)(((NF)(((NF)((*m).ay) * (NF)((*m).tx))) - (NF)(((NF)((*m).ax) * (NF)((*m).ty))))) / (NF)(d)));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, equals_B9a9bihKp19czsKgM7E4DwQLw)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m1, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m2, NF tol) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_BOOL T3_;
	NIM_BOOL T4_;
	NIM_BOOL T5_;
	nimfr_("equals", "basic2d.nim");
{	result = (NIM_BOOL)0;
	nimln_(301, "basic2d.nim");
	nimln_(305, "basic2d.nim");
	T1_ = (NIM_BOOL)0;
	nimln_(304, "basic2d.nim");
	T2_ = (NIM_BOOL)0;
	nimln_(303, "basic2d.nim");
	T3_ = (NIM_BOOL)0;
	nimln_(302, "basic2d.nim");
	T4_ = (NIM_BOOL)0;
	T5_ = (NIM_BOOL)0;
	T5_ = ((((NF)((*m1).ax) - (NF)((*m2).ax)) < 0? -(((NF)((*m1).ax) - (NF)((*m2).ax))) : (((NF)((*m1).ax) - (NF)((*m2).ax)))) <= tol);
	if (!(T5_)) goto LA6_;
	nimln_(303, "basic2d.nim");
	T5_ = ((((NF)((*m1).ay) - (NF)((*m2).ay)) < 0? -(((NF)((*m1).ay) - (NF)((*m2).ay))) : (((NF)((*m1).ay) - (NF)((*m2).ay)))) <= tol);
	LA6_: ;
	T4_ = T5_;
	if (!(T4_)) goto LA7_;
	nimln_(304, "basic2d.nim");
	T4_ = ((((NF)((*m1).bx) - (NF)((*m2).bx)) < 0? -(((NF)((*m1).bx) - (NF)((*m2).bx))) : (((NF)((*m1).bx) - (NF)((*m2).bx)))) <= tol);
	LA7_: ;
	T3_ = T4_;
	if (!(T3_)) goto LA8_;
	nimln_(305, "basic2d.nim");
	T3_ = ((((NF)((*m1).by) - (NF)((*m2).by)) < 0? -(((NF)((*m1).by) - (NF)((*m2).by))) : (((NF)((*m1).by) - (NF)((*m2).by)))) <= tol);
	LA8_: ;
	T2_ = T3_;
	if (!(T2_)) goto LA9_;
	nimln_(306, "basic2d.nim");
	T2_ = ((((NF)((*m1).tx) - (NF)((*m2).tx)) < 0? -(((NF)((*m1).tx) - (NF)((*m2).tx))) : (((NF)((*m1).tx) - (NF)((*m2).tx)))) <= tol);
	LA9_: ;
	T1_ = T2_;
	if (!(T1_)) goto LA10_;
	nimln_(307, "basic2d.nim");
	T1_ = ((((NF)((*m1).ty) - (NF)((*m2).ty)) < 0? -(((NF)((*m1).ty) - (NF)((*m2).ty))) : (((NF)((*m1).ty) - (NF)((*m2).ty)))) <= tol);
	LA10_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, eqtilde__ounRcA0VwHoq8l1TZM6OQg)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m1, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m2) {
	NIM_BOOL result;
	nimfr_("=~", "basic2d.nim");
	result = (NIM_BOOL)0;
	nimln_(310, "basic2d.nim");
	nimln_(312, "basic2d.nim");
	result = equals_B9a9bihKp19czsKgM7E4DwQLw(m1, m2, 9.9999999999999995e-007);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isIdentity_EmcS4cUhJ6G9ceMvF0sMJ4A)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m, NF tol) {
	NIM_BOOL result;
	nimfr_("isIdentity", "basic2d.nim");
{	result = (NIM_BOOL)0;
	nimln_(317, "basic2d.nim");
	result = equals_B9a9bihKp19czsKgM7E4DwQLw(m, (&IDMATRIX_DQf5P8YCykuDxNmZ5bvG7g), tol);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, apply_f06CKgVkHkCPrp69c1VkNTw)(tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m, NF* x, NF* y, NIM_BOOL translate) {
	nimfr_("apply", "basic2d.nim");
	nimln_(322, "basic2d.nim");
	{
		NF newx;
		if (!translate) goto LA3_;
		nimln_(323, "basic2d.nim");
		newx = ((NF)(((NF)(((NF)((*x)) * (NF)((*m).ax))) + (NF)(((NF)((*y)) * (NF)((*m).bx))))) + (NF)((*m).tx));
		nimln_(324, "basic2d.nim");
		(*y) = ((NF)(((NF)(((NF)((*x)) * (NF)((*m).ay))) + (NF)(((NF)((*y)) * (NF)((*m).by))))) + (NF)((*m).ty));
		nimln_(325, "basic2d.nim");
		(*x) = newx;
	}
	goto LA1_;
	LA3_: ;
	{
		NF newx_2;
		nimln_(327, "basic2d.nim");
		newx_2 = ((NF)(((NF)((*x)) * (NF)((*m).ax))) + (NF)(((NF)((*y)) * (NF)((*m).bx))));
		nimln_(328, "basic2d.nim");
		(*y) = ((NF)(((NF)((*x)) * (NF)((*m).ay))) + (NF)(((NF)((*y)) * (NF)((*m).by))));
		nimln_(329, "basic2d.nim");
		(*x) = newx_2;
	}
	LA1_: ;
	popFrame();
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d)(NF x, NF y) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("vector2d", "basic2d.nim");
	nimln_(337, "basic2d.nim");
	result.x = x;
	nimln_(338, "basic2d.nim");
	result.y = y;
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, polarVector2d_2K5U8o4UaLz89akm1AvvS6A)(NF ang, NF len) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	NF T1_;
	NF T2_;
	nimfr_("polarVector2d", "basic2d.nim");
	nimln_(342, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = cos(ang);
	result.x = ((NF)(T1_) * (NF)(len));
	nimln_(343, "basic2d.nim");
	T2_ = (NF)0;
	T2_ = sin(ang);
	result.y = ((NF)(T2_) * (NF)(len));
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, slopeVector2d_2417hh0F6xyDekjIlOe21A)(NF slope, NF len) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	NF ang;
	NF T1_;
	NF T2_;
	nimfr_("slopeVector2d", "basic2d.nim");
	nimln_(348, "basic2d.nim");
	ang = atan(slope);
	nimln_(349, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = cos(ang);
	result.x = ((NF)(T1_) * (NF)(len));
	nimln_(350, "basic2d.nim");
	T2_ = (NF)0;
	T2_ = sin(ang);
	result.y = ((NF)(T2_) * (NF)(len));
	popFrame();
	return result;
}

static N_INLINE(NF, len_MpSCgcxEZtYWTBuEMJUaIgbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	NF result;
	nimfr_("len", "basic2d.nim");
	result = (NF)0;
	nimln_(353, "basic2d.nim");
	nimln_(354, "basic2d.nim");
	result = sqrt(((NF)(((NF)(v.x) * (NF)(v.x))) + (NF)(((NF)(v.y) * (NF)(v.y)))));
	popFrame();
	return result;
}

static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x, NF y) {
	nimfr_("*=", "system.nim");
	nimln_(3544, "system.nim");
	(*x) = ((NF)((*x)) * (NF)(y));
	popFrame();
}

N_NIMCALL(void, leneq__d7vvQbGwGw9aDTglUln0OPg)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, NF newlen) {
	NF fac;
	NF T1_;
	nimfr_("len=", "basic2d.nim");
{	nimln_(358, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = len_MpSCgcxEZtYWTBuEMJUaIgbasic2d((*v));
	fac = ((NF)(newlen) / (NF)(T1_));
	nimln_(360, "basic2d.nim");
	{
		if (!(newlen == 0.0)) goto LA4_;
		nimln_(361, "basic2d.nim");
		(*v).x = 0.0;
		nimln_(362, "basic2d.nim");
		(*v).y = 0.0;
		nimln_(363, "basic2d.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(365, "basic2d.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = (fac == INF);
		if (T8_) goto LA9_;
		T8_ = (fac == -INF);
		LA9_: ;
		if (!T8_) goto LA10_;
		nimln_(368, "basic2d.nim");
		(*v).x = newlen;
		nimln_(369, "basic2d.nim");
		(*v).y = 0.0;
	}
	goto LA6_;
	LA10_: ;
	{
		nimln_(371, "basic2d.nim");
		stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*v).x), fac);
		nimln_(372, "basic2d.nim");
		stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*v).y), fac);
	}
	LA6_: ;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NF, sqrLen_MpSCgcxEZtYWTBuEMJUaIg_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	NF result;
	nimfr_("sqrLen", "basic2d.nim");
	result = (NF)0;
	nimln_(375, "basic2d.nim");
	nimln_(377, "basic2d.nim");
	result = ((NF)(((NF)(v.x) * (NF)(v.x))) + (NF)(((NF)(v.y) * (NF)(v.y))));
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y) {
	nimfr_("+=", "system.nim");
	nimln_(3534, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

N_NIMCALL(NF, angle_jpx9aVKvbHuECXQ3uv5sdGA)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	NF result;
	nimfr_("angle", "basic2d.nim");
	result = (NF)0;
	nimln_(382, "basic2d.nim");
	result = atan2(v.y, v.x);
	nimln_(383, "basic2d.nim");
	{
		if (!(result < 0.0)) goto LA3_;
		pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&result), 6.2831853071795862e+000);
	}
	LA3_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, dollar__KNZuzaUJrmopxmNu9aZOB9bA)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	nimfr_("$", "basic2d.nim");
	result = (NimStringDesc*)0;
	nimln_(387, "basic2d.nim");
	result = rtos_3imJPLy7In9aRjL9c9aiFr9c3g(v.x);
	nimln_(388, "basic2d.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_2));
	nimln_(389, "basic2d.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rtos_3imJPLy7In9aRjL9c9aiFr9c3g(v.y);
	result = resizeString(result, T1_->Sup.len + 0);
appendString(result, T1_);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, amp__H2WQIQQ2D7pJCqSLsOLCxQ)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("&", "basic2d.nim");
	nimln_(400, "basic2d.nim");
	result.x = ((NF)(((NF)(v.x) * (NF)((*m).ax))) + (NF)(((NF)(v.y) * (NF)((*m).bx))));
	nimln_(401, "basic2d.nim");
	result.y = ((NF)(((NF)(v.x) * (NF)((*m).ay))) + (NF)(((NF)(v.y) * (NF)((*m).by))));
	popFrame();
	return result;
}

static N_INLINE(void, ampeq__b7en8I9a5jBX5TdB9cEdlKuwbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* m) {
	NF newx;
	nimfr_("&=", "basic2d.nim");
	nimln_(412, "basic2d.nim");
	newx = ((NF)(((NF)((*v).x) * (NF)((*m).ax))) + (NF)(((NF)((*v).y) * (NF)((*m).bx))));
	nimln_(413, "basic2d.nim");
	(*v).y = ((NF)(((NF)((*v).x) * (NF)((*m).ay))) + (NF)(((NF)((*v).y) * (NF)((*m).by))));
	nimln_(414, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

static N_INLINE(void, slasheq__7kHiltrvRlcg6wSYR3CxAwsystem)(NF* x, NF y) {
	nimfr_("/=", "system.nim");
	nimln_(3548, "system.nim");
	(*x) = ((NF)((*x)) / (NF)(y));
	popFrame();
}

N_NIMCALL(NIM_BOOL, tryNormalize_BqsLwyP1Q2mmowpWiNwdzw)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v) {
	NIM_BOOL result;
	NF mag;
	nimfr_("tryNormalize", "basic2d.nim");
{	result = (NIM_BOOL)0;
	nimln_(422, "basic2d.nim");
	mag = len_MpSCgcxEZtYWTBuEMJUaIgbasic2d((*v));
	nimln_(424, "basic2d.nim");
	{
		if (!(mag == 0.0)) goto LA3_;
		nimln_(425, "basic2d.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(427, "basic2d.nim");
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&(*v).x), mag);
	nimln_(428, "basic2d.nim");
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&(*v).y), mag);
	nimln_(429, "basic2d.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, normalize_D082ouE4v9aynDe1fZCQY0Qbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v) {
	nimfr_("normalize", "basic2d.nim");
	nimln_(435, "basic2d.nim");
	{
		NIM_BOOL T3_;
		tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA* e;
		NimStringDesc* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = tryNormalize_BqsLwyP1Q2mmowpWiNwdzw(v);
		if (!!(T3_)) goto LA4_;
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*) newObj((&NTI_BdGSl5vgXXoo8kaIdXXVyw_), sizeof(tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA));
		(*e).Sup.Sup.Sup.m_type = (&NTI_p6OJ2WGp1zYZkMyhPlJPZA_);
		nimln_(436, "basic2d.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_4));
		if (T6_) nimGCunrefNoCycle(T6_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(436, "basic2d.nim");
		raiseException((Exception*)e, "DivByZeroError");
	}
	LA4_: ;
	popFrame();
}

N_NIMCALL(void, transformNorm_eCblPLXj9bpzHBxKqDFVHSQ)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t) {
	NF d;
	NF newx;
	nimfr_("transformNorm", "basic2d.nim");
	nimln_(450, "basic2d.nim");
	d = determinant_qbdsEeWv1HhmDNAQvcsJyw(t);
	nimln_(451, "basic2d.nim");
	{
		tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA* e;
		NimStringDesc* T5_;
		if (!(d == 0.0)) goto LA3_;
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*) newObj((&NTI_BdGSl5vgXXoo8kaIdXXVyw_), sizeof(tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA));
		(*e).Sup.Sup.Sup.m_type = (&NTI_p6OJ2WGp1zYZkMyhPlJPZA_);
		nimln_(452, "basic2d.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_5));
		if (T5_) nimGCunrefNoCycle(T5_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(452, "basic2d.nim");
		raiseException((Exception*)e, "DivByZeroError");
	}
	LA3_: ;
	nimln_(453, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)((*t).by) * (NF)((*v).x))) - (NF)(((NF)((*t).ay) * (NF)((*v).y))))) / (NF)(d));
	nimln_(454, "basic2d.nim");
	(*v).y = ((NF)(((NF)(((NF)((*t).ax) * (NF)((*v).y))) - (NF)(((NF)((*t).bx) * (NF)((*v).x))))) / (NF)(d));
	nimln_(455, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

N_NIMCALL(void, transformInv_eCblPLXj9bpzHBxKqDFVHSQ_2)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t) {
	NF d;
	NF newx;
	nimfr_("transformInv", "basic2d.nim");
	nimln_(463, "basic2d.nim");
	d = determinant_qbdsEeWv1HhmDNAQvcsJyw(t);
	nimln_(465, "basic2d.nim");
	{
		tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA* e;
		NimStringDesc* T5_;
		if (!(d == 0.0)) goto LA3_;
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*) newObj((&NTI_BdGSl5vgXXoo8kaIdXXVyw_), sizeof(tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA));
		(*e).Sup.Sup.Sup.m_type = (&NTI_p6OJ2WGp1zYZkMyhPlJPZA_);
		nimln_(466, "basic2d.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_5));
		if (T5_) nimGCunrefNoCycle(T5_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(466, "basic2d.nim");
		raiseException((Exception*)e, "DivByZeroError");
	}
	LA3_: ;
	nimln_(468, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)((*t).by) * (NF)((*v).x))) - (NF)(((NF)((*t).bx) * (NF)((*v).y))))) / (NF)(d));
	nimln_(469, "basic2d.nim");
	(*v).y = ((NF)(((NF)(((NF)((*t).ax) * (NF)((*v).y))) - (NF)(((NF)((*t).ay) * (NF)((*v).x))))) / (NF)(d));
	nimln_(470, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

N_NIMCALL(void, transformNormInv_eCblPLXj9bpzHBxKqDFVHSQ_3)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t) {
	NF newx;
	nimfr_("transformNormInv", "basic2d.nim");
	nimln_(485, "basic2d.nim");
	newx = ((NF)(((NF)((*t).ay) * (NF)((*v).y))) + (NF)(((NF)((*t).ax) * (NF)((*v).x))));
	nimln_(486, "basic2d.nim");
	(*v).y = ((NF)(((NF)((*t).by) * (NF)((*v).y))) + (NF)(((NF)((*t).bx) * (NF)((*v).x))));
	nimln_(487, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

static N_INLINE(void, rotate90_D082ouE4v9aynDe1fZCQY0Q_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v) {
	NF T1_;
	nimfr_("rotate90", "basic2d.nim");
	nimln_(492, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = (*v).x;
	(*v).x = (*v).y;
	(*v).y = T1_;
	nimln_(493, "basic2d.nim");
	(*v).x = -((*v).x);
	popFrame();
}

static N_INLINE(void, rotate180_D082ouE4v9aynDe1fZCQY0Q_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v) {
	nimfr_("rotate180", "basic2d.nim");
	nimln_(498, "basic2d.nim");
	(*v).x = -((*v).x);
	nimln_(499, "basic2d.nim");
	(*v).y = -((*v).y);
	popFrame();
}

static N_INLINE(void, rotate270_D082ouE4v9aynDe1fZCQY0Q_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v) {
	NF T1_;
	nimfr_("rotate270", "basic2d.nim");
	nimln_(504, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = (*v).x;
	(*v).x = (*v).y;
	(*v).y = T1_;
	nimln_(505, "basic2d.nim");
	(*v).y = -((*v).y);
	popFrame();
}

N_NIMCALL(void, rotate_NNq9cyE9a9aA9bP29bAGLZEPkeA)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, NF rad) {
	NF s;
	NF c;
	NF newx;
	nimfr_("rotate", "basic2d.nim");
	nimln_(510, "basic2d.nim");
	s = sin(rad);
	nimln_(511, "basic2d.nim");
	c = cos(rad);
	nimln_(512, "basic2d.nim");
	newx = ((NF)(((NF)(c) * (NF)((*v).x))) - (NF)(((NF)(s) * (NF)((*v).y))));
	nimln_(513, "basic2d.nim");
	(*v).y = ((NF)(((NF)(c) * (NF)((*v).y))) + (NF)(((NF)(s) * (NF)((*v).x))));
	nimln_(514, "basic2d.nim");
	(*v).x = newx;
	popFrame();
}

static N_INLINE(void, scale_8I9c8xBfd3ZYUR4t5su9aiEAbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, NF fac) {
	nimfr_("scale", "basic2d.nim");
	nimln_(518, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*v).x), fac);
	nimln_(519, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*v).y), fac);
	popFrame();
}

static N_INLINE(void, stretch_qiBYYSjb6dcXtdMjL5g4bAbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, NF facx, NF facy) {
	nimfr_("stretch", "basic2d.nim");
	nimln_(524, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*v).x), facx);
	nimln_(525, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*v).y), facy);
	popFrame();
}

N_NIMCALL(void, mirror_kLaFeSdfrShnu03l7Gei0g)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* v, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA mirrvec) {
	NF sqx;
	NF sqy;
	NF nd;
	NF xy2;
	NF sqd;
	NF newx;
	nimfr_("mirror", "basic2d.nim");
{	nimln_(530, "basic2d.nim");
	sqx = ((NF)(mirrvec.x) * (NF)(mirrvec.x));
	nimln_(531, "basic2d.nim");
	sqy = ((NF)(mirrvec.y) * (NF)(mirrvec.y));
	nimln_(532, "basic2d.nim");
	nd = ((NF)(1.0000000000000000e+000) / (NF)(((NF)(sqx) + (NF)(sqy))));
	nimln_(533, "basic2d.nim");
	xy2 = ((NF)(((NF)(((NF)(mirrvec.x) * (NF)(mirrvec.y))) * (NF)(2.0000000000000000e+000))) * (NF)(nd));
	nimln_(534, "basic2d.nim");
	sqd = ((NF)(nd) * (NF)(((NF)(sqx) - (NF)(sqy))));
	nimln_(536, "basic2d.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (nd == INF);
		if (T3_) goto LA4_;
		T3_ = (nd == -INF);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(537, "basic2d.nim");
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(539, "basic2d.nim");
	newx = ((NF)(((NF)(xy2) * (NF)((*v).y))) + (NF)(((NF)(sqd) * (NF)((*v).x))));
	nimln_(540, "basic2d.nim");
	(*v).y = ((NF)(((NF)((*v).x) * (NF)(xy2))) - (NF)(((NF)(sqd) * (NF)((*v).y))));
	nimln_(541, "basic2d.nim");
	(*v).x = newx;
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__8A0se4zNNtldWGqC9aM5sgw)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("-", "basic2d.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(546, "basic2d.nim");
	result.x = -(v.x);
	nimln_(547, "basic2d.nim");
	result.y = -(v.y);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, plus__N47oJl3jYu7DD4h0uckZNAbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("+", "basic2d.nim");
	nimln_(121, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a.x) + (NF)(b.x)), ((NF)(a.y) + (NF)(b.y)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, plus__tGCcuKwuFv3czilpjeV5TAbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, NF b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("+", "basic2d.nim");
	nimln_(122, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a.x) + (NF)(b)), ((NF)(a.y) + (NF)(b)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, plus__vh9ayTY2e7ACJx9a0rD3b0Jgbasic2d)(NF a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("+", "basic2d.nim");
	nimln_(123, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a) + (NF)(b.x)), ((NF)(a) + (NF)(b.y)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__N47oJl3jYu7DD4h0uckZNA_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("-", "basic2d.nim");
	nimln_(121, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a.x) - (NF)(b.x)), ((NF)(a.y) - (NF)(b.y)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__tGCcuKwuFv3czilpjeV5TA_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, NF b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("-", "basic2d.nim");
	nimln_(122, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a.x) - (NF)(b)), ((NF)(a.y) - (NF)(b)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__vh9ayTY2e7ACJx9a0rD3b0Jg_2basic2d)(NF a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("-", "basic2d.nim");
	nimln_(123, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a) - (NF)(b.x)), ((NF)(a) - (NF)(b.y)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, star__N47oJl3jYu7DD4h0uckZNA_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("*", "basic2d.nim");
	nimln_(121, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a.x) * (NF)(b.x)), ((NF)(a.y) * (NF)(b.y)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, star__tGCcuKwuFv3czilpjeV5TA_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, NF b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("*", "basic2d.nim");
	nimln_(122, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a.x) * (NF)(b)), ((NF)(a.y) * (NF)(b)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, star__vh9ayTY2e7ACJx9a0rD3b0Jg_3basic2d)(NF a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("*", "basic2d.nim");
	nimln_(123, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a) * (NF)(b.x)), ((NF)(a) * (NF)(b.y)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, slash__N47oJl3jYu7DD4h0uckZNA_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("/", "basic2d.nim");
	nimln_(121, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a.x) / (NF)(b.x)), ((NF)(a.y) / (NF)(b.y)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, slash__tGCcuKwuFv3czilpjeV5TA_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA a, NF b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("/", "basic2d.nim");
	nimln_(122, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a.x) / (NF)(b)), ((NF)(a.y) / (NF)(b)));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, slash__vh9ayTY2e7ACJx9a0rD3b0Jg_4basic2d)(NF a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("/", "basic2d.nim");
	nimln_(123, "basic2d.nim");
	result = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(((NF)(a) / (NF)(b.x)), ((NF)(a) / (NF)(b.y)));
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__jxViqne0KjwGpG3r4qzcWQbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	nimfr_("+=", "basic2d.nim");
	nimln_(127, "basic2d.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*a).x), b.x);
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*a).y), b.y);
	popFrame();
}

static N_INLINE(void, pluseq__rWWFNP2c6vvhU6RKFR7VXwbasic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, NF b) {
	nimfr_("+=", "basic2d.nim");
	nimln_(128, "basic2d.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*a).x), b);
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*a).y), b);
	popFrame();
}

static N_INLINE(void, minuseq__7kHiltrvRlcg6wSYR3CxAwtimes)(NF* x, NF y) {
	nimfr_("-=", "system.nim");
	nimln_(3539, "system.nim");
	(*x) = ((NF)((*x)) - (NF)(y));
	popFrame();
}

static N_INLINE(void, minuseq__jxViqne0KjwGpG3r4qzcWQ_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	nimfr_("-=", "basic2d.nim");
	nimln_(127, "basic2d.nim");
	minuseq__7kHiltrvRlcg6wSYR3CxAwtimes((&(*a).x), b.x);
	minuseq__7kHiltrvRlcg6wSYR3CxAwtimes((&(*a).y), b.y);
	popFrame();
}

static N_INLINE(void, minuseq__rWWFNP2c6vvhU6RKFR7VXw_2basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, NF b) {
	nimfr_("-=", "basic2d.nim");
	nimln_(128, "basic2d.nim");
	minuseq__7kHiltrvRlcg6wSYR3CxAwtimes((&(*a).x), b);
	minuseq__7kHiltrvRlcg6wSYR3CxAwtimes((&(*a).y), b);
	popFrame();
}

static N_INLINE(void, stareq__jxViqne0KjwGpG3r4qzcWQ_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	nimfr_("*=", "basic2d.nim");
	nimln_(127, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*a).x), b.x);
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*a).y), b.y);
	popFrame();
}

static N_INLINE(void, stareq__rWWFNP2c6vvhU6RKFR7VXw_3basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, NF b) {
	nimfr_("*=", "basic2d.nim");
	nimln_(128, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*a).x), b);
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*a).y), b);
	popFrame();
}

static N_INLINE(void, slasheq__jxViqne0KjwGpG3r4qzcWQ_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA b) {
	nimfr_("/=", "basic2d.nim");
	nimln_(127, "basic2d.nim");
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&(*a).x), b.x);
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&(*a).y), b.y);
	popFrame();
}

static N_INLINE(void, slasheq__rWWFNP2c6vvhU6RKFR7VXw_4basic2d)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA* a, NF b) {
	nimfr_("/=", "basic2d.nim");
	nimln_(128, "basic2d.nim");
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&(*a).x), b);
	slasheq__7kHiltrvRlcg6wSYR3CxAwsystem((&(*a).y), b);
	popFrame();
}

N_NIMCALL(NF, dot_UMotgrIsXNHj9b9cjNtuOxcA)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2) {
	NF result;
	nimfr_("dot", "basic2d.nim");
{	result = (NF)0;
	nimln_(563, "basic2d.nim");
	result = ((NF)(((NF)(v1.x) * (NF)(v2.x))) + (NF)(((NF)(v1.y) * (NF)(v2.y))));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, cross_UMotgrIsXNHj9b9cjNtuOxcA_2)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2) {
	NF result;
	nimfr_("cross", "basic2d.nim");
{	result = (NF)0;
	nimln_(569, "basic2d.nim");
	result = ((NF)(((NF)(v1.x) * (NF)(v2.y))) - (NF)(((NF)(v1.y) * (NF)(v2.x))));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, equals_YlkCr9aLbK8cRfctU27mT0g)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2, NF tol) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("equals", "basic2d.nim");
{	result = (NIM_BOOL)0;
	nimln_(573, "basic2d.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((((NF)(v2.x) - (NF)(v1.x)) < 0? -(((NF)(v2.x) - (NF)(v1.x))) : (((NF)(v2.x) - (NF)(v1.x)))) <= tol);
	if (!(T1_)) goto LA2_;
	T1_ = ((((NF)(v2.y) - (NF)(v1.y)) < 0? -(((NF)(v2.y) - (NF)(v1.y))) : (((NF)(v2.y) - (NF)(v1.y)))) <= tol);
	LA2_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, eqtilde__YiLpvs3yoG4GgNef1O8Q0Q)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2) {
	NIM_BOOL result;
	nimfr_("=~", "basic2d.nim");
	result = (NIM_BOOL)0;
	nimln_(576, "basic2d.nim");
	nimln_(578, "basic2d.nim");
	result = equals_YlkCr9aLbK8cRfctU27mT0g(v1, v2, 9.9999999999999995e-007);
	popFrame();
	return result;
}

N_NIMCALL(NF, angleTo_UMotgrIsXNHj9b9cjNtuOxcA_3)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2) {
	NF result;
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA nv1;
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA nv2;
	NF T9_;
	nimfr_("angleTo", "basic2d.nim");
{	result = (NF)0;
	nimln_(584, "basic2d.nim");
	nv1 = v1;
	nimln_(585, "basic2d.nim");
	nv2 = v2;
	nimln_(586, "basic2d.nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T6_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = tryNormalize_BqsLwyP1Q2mmowpWiNwdzw((&nv1));
		T3_ = !(T4_);
		if (T3_) goto LA5_;
		T6_ = (NIM_BOOL)0;
		T6_ = tryNormalize_BqsLwyP1Q2mmowpWiNwdzw((&nv2));
		T3_ = !(T6_);
		LA5_: ;
		if (!T3_) goto LA7_;
		nimln_(587, "basic2d.nim");
		result = 0.0;
		goto BeforeRet_;
	}
	LA7_: ;
	nimln_(588, "basic2d.nim");
	T9_ = (NF)0;
	T9_ = dot_UMotgrIsXNHj9b9cjNtuOxcA(nv1, nv2);
	result = safeArccos_3uSopz0panQtDF7zUu7C9aA(T9_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, angleCCW_UMotgrIsXNHj9b9cjNtuOxcA_4)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2) {
	NF result;
	NF a;
	nimfr_("angleCCW", "basic2d.nim");
{	result = (NF)0;
	nimln_(593, "basic2d.nim");
	a = angleTo_UMotgrIsXNHj9b9cjNtuOxcA_3(v1, v2);
	nimln_(594, "basic2d.nim");
	{
		NF T3_;
		T3_ = (NF)0;
		T3_ = cross_UMotgrIsXNHj9b9cjNtuOxcA_2(v1, v2);
		if (!(0.0 <= T3_)) goto LA4_;
		nimln_(595, "basic2d.nim");
		result = a;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(596, "basic2d.nim");
	result = ((NF)(6.2831853071795862e+000) - (NF)(a));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, angleCW_UMotgrIsXNHj9b9cjNtuOxcA_5)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2) {
	NF result;
	NF a;
	nimfr_("angleCW", "basic2d.nim");
{	result = (NF)0;
	nimln_(601, "basic2d.nim");
	a = angleTo_UMotgrIsXNHj9b9cjNtuOxcA_3(v1, v2);
	nimln_(602, "basic2d.nim");
	{
		NF T3_;
		T3_ = (NF)0;
		T3_ = cross_UMotgrIsXNHj9b9cjNtuOxcA_2(v1, v2);
		if (!(T3_ <= 0.0)) goto LA4_;
		nimln_(603, "basic2d.nim");
		result = a;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(604, "basic2d.nim");
	result = ((NF)(6.2831853071795862e+000) - (NF)(a));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, turnAngle_UMotgrIsXNHj9b9cjNtuOxcA_6)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2) {
	NF result;
	NF a;
	nimfr_("turnAngle", "basic2d.nim");
{	result = (NF)0;
	nimln_(609, "basic2d.nim");
	a = angleTo_UMotgrIsXNHj9b9cjNtuOxcA_3(v1, v2);
	nimln_(610, "basic2d.nim");
	{
		NF T3_;
		T3_ = (NF)0;
		T3_ = cross_UMotgrIsXNHj9b9cjNtuOxcA_2(v1, v2);
		if (!(T3_ <= 0.0)) goto LA4_;
		nimln_(611, "basic2d.nim");
		result = -(a);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(612, "basic2d.nim");
	result = a;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, bisect_BkRBc2VZG9as1tDSyv9bgZYQ)(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v1, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v2) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	NF vmag1;
	NF vmag2;
	NF x1;
	NF y1;
	NF x2;
	NF y2;
	nimfr_("bisect", "basic2d.nim");
{	nimln_(620, "basic2d.nim");
	vmag1 = len_MpSCgcxEZtYWTBuEMJUaIgbasic2d(v1);
	nimln_(621, "basic2d.nim");
	vmag2 = len_MpSCgcxEZtYWTBuEMJUaIgbasic2d(v2);
	nimln_(625, "basic2d.nim");
	{
		if (!(vmag1 == 0.0)) goto LA3_;
		nimln_(626, "basic2d.nim");
		{
			if (!(vmag2 == 0.0)) goto LA7_;
			nimln_(627, "basic2d.nim");
			result = XAXIS_cHisHYvnFnWkQFsXQwR8LA;
			goto BeforeRet_;
		}
		LA7_: ;
		nimln_(628, "basic2d.nim");
		vmag1 = 1.0000000000000000e+000;
	}
	LA3_: ;
	nimln_(629, "basic2d.nim");
	{
		if (!(vmag2 == 0.0)) goto LA11_;
		vmag2 = 1.0000000000000000e+000;
	}
	LA11_: ;
	nimln_(632, "basic2d.nim");
	x1 = ((NF)(v1.x) / (NF)(vmag1));
	nimln_(633, "basic2d.nim");
	y1 = ((NF)(v1.y) / (NF)(vmag1));
	nimln_(634, "basic2d.nim");
	x2 = ((NF)(v2.x) / (NF)(vmag2));
	nimln_(635, "basic2d.nim");
	y2 = ((NF)(v2.y) / (NF)(vmag2));
	nimln_(637, "basic2d.nim");
	result.x = ((NF)(((NF)(x1) + (NF)(x2))) * (NF)(5.0000000000000000e-001));
	nimln_(638, "basic2d.nim");
	result.y = ((NF)(((NF)(y1) + (NF)(y2))) * (NF)(5.0000000000000000e-001));
	nimln_(640, "basic2d.nim");
	{
		NIM_BOOL T15_;
		T15_ = (NIM_BOOL)0;
		T15_ = tryNormalize_BqsLwyP1Q2mmowpWiNwdzw((&result));
		if (!!(T15_)) goto LA16_;
		nimln_(644, "basic2d.nim");
		result.x = -(y1);
		nimln_(645, "basic2d.nim");
		result.y = x1;
	}
	LA16_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, point2d_4HtTb6DBuFYILwb7lqld9agbasic2d)(NF x, NF y) {
	tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug result;
	nimfr_("point2d", "basic2d.nim");
	nimln_(654, "basic2d.nim");
	result.x = x;
	nimln_(655, "basic2d.nim");
	result.y = y;
	popFrame();
	return result;
}

N_NIMCALL(NF, sqrDist_inohp9bGa7FVYBb9biOHHX4g)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b) {
	NF result;
	NF dx;
	NF dy;
	nimfr_("sqrDist", "basic2d.nim");
	result = (NF)0;
	nimln_(659, "basic2d.nim");
	dx = ((NF)(b.x) - (NF)(a.x));
	nimln_(660, "basic2d.nim");
	dy = ((NF)(b.y) - (NF)(a.y));
	nimln_(661, "basic2d.nim");
	result = ((NF)(((NF)(dx) * (NF)(dx))) + (NF)(((NF)(dy) * (NF)(dy))));
	popFrame();
	return result;
}

static N_INLINE(NF, dist_8eiFVGqElBlsuJ69apJn34Qbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b) {
	NF result;
	NF T1_;
	nimfr_("dist", "basic2d.nim");
	result = (NF)0;
	nimln_(665, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = sqrDist_inohp9bGa7FVYBb9biOHHX4g(a, b);
	result = sqrt(T1_);
	popFrame();
	return result;
}

N_NIMCALL(NF, angle_inohp9bGa7FVYBb9biOHHX4g_2)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b) {
	NF result;
	NF dx;
	NF dy;
	nimfr_("angle", "basic2d.nim");
	result = (NF)0;
	nimln_(669, "basic2d.nim");
	dx = ((NF)(b.x) - (NF)(a.x));
	nimln_(670, "basic2d.nim");
	dy = ((NF)(b.y) - (NF)(a.y));
	nimln_(671, "basic2d.nim");
	result = atan2(dy, dx);
	nimln_(672, "basic2d.nim");
	{
		if (!(result < 0.0)) goto LA3_;
		nimln_(673, "basic2d.nim");
		pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&result), 6.2831853071795862e+000);
	}
	LA3_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, dollar__4EQ4uWvU5Cm07oTXBQtD7Q)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	nimfr_("$", "basic2d.nim");
	result = (NimStringDesc*)0;
	nimln_(677, "basic2d.nim");
	result = rtos_3imJPLy7In9aRjL9c9aiFr9c3g(p.x);
	nimln_(678, "basic2d.nim");
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_2));
	nimln_(679, "basic2d.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rtos_3imJPLy7In9aRjL9c9aiFr9c3g(p.y);
	result = resizeString(result, T1_->Sup.len + 0);
appendString(result, T1_);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, amp__PI6cZrDDf2SDzREFmRVFywbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t) {
	tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug result;
	nimfr_("&", "basic2d.nim");
	nimln_(688, "basic2d.nim");
	result.x = ((NF)(((NF)(((NF)(p.x) * (NF)((*t).ax))) + (NF)(((NF)(p.y) * (NF)((*t).bx))))) + (NF)((*t).tx));
	nimln_(689, "basic2d.nim");
	result.y = ((NF)(((NF)(((NF)(p.x) * (NF)((*t).ay))) + (NF)(((NF)(p.y) * (NF)((*t).by))))) + (NF)((*t).ty));
	popFrame();
	return result;
}

static N_INLINE(void, ampeq__Mcrst0GjTEBJbss0HgUdnAbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t) {
	NF newx;
	nimfr_("&=", "basic2d.nim");
	nimln_(693, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)((*p).x) * (NF)((*t).ax))) + (NF)(((NF)((*p).y) * (NF)((*t).bx))))) + (NF)((*t).tx));
	nimln_(694, "basic2d.nim");
	(*p).y = ((NF)(((NF)(((NF)((*p).x) * (NF)((*t).ay))) + (NF)(((NF)((*p).y) * (NF)((*t).by))))) + (NF)((*t).ty));
	nimln_(695, "basic2d.nim");
	(*p).x = newx;
	popFrame();
}

static N_INLINE(void, transformInv_Mcrst0GjTEBJbss0HgUdnA_2basic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Matrix2d_apt8v8Iw9bh7km28IcOJIkg* t) {
	NF d;
	NF newx;
	nimfr_("transformInv", "basic2d.nim");
	nimln_(706, "basic2d.nim");
	d = determinant_qbdsEeWv1HhmDNAQvcsJyw(t);
	nimln_(707, "basic2d.nim");
	{
		tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA* e;
		NimStringDesc* T5_;
		if (!(d == 0.0)) goto LA3_;
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*)0;
		nimln_(2702, "system.nim");
		e = (tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA*) newObj((&NTI_BdGSl5vgXXoo8kaIdXXVyw_), sizeof(tyObject_DivByZeroError_p6OJ2WGp1zYZkMyhPlJPZA));
		(*e).Sup.Sup.Sup.m_type = (&NTI_p6OJ2WGp1zYZkMyhPlJPZA_);
		nimln_(708, "basic2d.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_3));
		if (T5_) nimGCunrefNoCycle(T5_);
		nimln_(2697, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(708, "basic2d.nim");
		raiseException((Exception*)e, "DivByZeroError");
	}
	LA3_: ;
	nimln_(710, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)(((NF)(((NF)((*t).bx) * (NF)((*t).ty))) - (NF)(((NF)((*t).by) * (NF)((*t).tx))))) + (NF)(((NF)((*p).x) * (NF)((*t).by))))) - (NF)(((NF)((*p).y) * (NF)((*t).bx))))) / (NF)(d));
	nimln_(711, "basic2d.nim");
	(*p).y = ((NF)(-(((NF)(((NF)(((NF)(((NF)((*t).ax) * (NF)((*t).ty))) - (NF)(((NF)((*t).ay) * (NF)((*t).tx))))) + (NF)(((NF)((*p).x) * (NF)((*t).ay))))) - (NF)(((NF)((*p).y) * (NF)((*t).ax)))))) / (NF)(d));
	nimln_(712, "basic2d.nim");
	(*p).x = newx;
	popFrame();
}

static N_INLINE(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, plus__q81dFZGTLUb4p1FMszt1zAbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug result;
	nimfr_("+", "basic2d.nim");
	nimln_(718, "basic2d.nim");
	result.x = ((NF)(p.x) + (NF)(v.x));
	nimln_(719, "basic2d.nim");
	result.y = ((NF)(p.y) + (NF)(v.y));
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__FhMmgV9c9csOjbyaRVR6fA3wbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	nimfr_("+=", "basic2d.nim");
	nimln_(723, "basic2d.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*p).x), v.x);
	nimln_(724, "basic2d.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*p).y), v.y);
	popFrame();
}

static N_INLINE(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, minus__q81dFZGTLUb4p1FMszt1zA_2basic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug result;
	nimfr_("-", "basic2d.nim");
	nimln_(729, "basic2d.nim");
	result.x = ((NF)(p.x) - (NF)(v.x));
	nimln_(730, "basic2d.nim");
	result.y = ((NF)(p.y) - (NF)(v.y));
	popFrame();
	return result;
}

static N_INLINE(tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA, minus__K59coQjPs7Tllh50beRwK1Abasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p1, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p2) {
	tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA result;
	nimfr_("-", "basic2d.nim");
	nimln_(734, "basic2d.nim");
	result.x = ((NF)(p1.x) - (NF)(p2.x));
	nimln_(735, "basic2d.nim");
	result.y = ((NF)(p1.y) - (NF)(p2.y));
	popFrame();
	return result;
}

static N_INLINE(void, minuseq__FhMmgV9c9csOjbyaRVR6fA3w_2basic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	nimfr_("-=", "basic2d.nim");
	nimln_(739, "basic2d.nim");
	minuseq__7kHiltrvRlcg6wSYR3CxAwtimes((&(*p).x), v.x);
	nimln_(740, "basic2d.nim");
	minuseq__7kHiltrvRlcg6wSYR3CxAwtimes((&(*p).y), v.y);
	popFrame();
}

static N_INLINE(NIM_BOOL, equals_G7pjBf3BhCkaFjfbrpRp5Abasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p1, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p2, NF tol) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_("equals", "basic2d.nim");
{	result = (NIM_BOOL)0;
	nimln_(744, "basic2d.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = ((((NF)(p2.x) - (NF)(p1.x)) < 0? -(((NF)(p2.x) - (NF)(p1.x))) : (((NF)(p2.x) - (NF)(p1.x)))) <= tol);
	if (!(T1_)) goto LA2_;
	T1_ = ((((NF)(p2.y) - (NF)(p1.y)) < 0? -(((NF)(p2.y) - (NF)(p1.y))) : (((NF)(p2.y) - (NF)(p1.y)))) <= tol);
	LA2_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqtilde__l72v28qwjjOADB5JC9adeDwbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p1, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p2) {
	NIM_BOOL result;
	nimfr_("=~", "basic2d.nim");
	result = (NIM_BOOL)0;
	nimln_(747, "basic2d.nim");
	nimln_(749, "basic2d.nim");
	result = equals_G7pjBf3BhCkaFjfbrpRp5Abasic2d(p1, p2, 9.9999999999999995e-007);
	popFrame();
	return result;
}

N_NIMCALL(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, polar_R1XspyRFM0GHMX3bpfn6oQ)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, NF ang, NF dist) {
	tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug result;
	NF T1_;
	NF T2_;
	nimfr_("polar", "basic2d.nim");
	nimln_(753, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = cos(ang);
	result.x = ((NF)(p.x) + (NF)(((NF)(T1_) * (NF)(dist))));
	nimln_(754, "basic2d.nim");
	T2_ = (NF)0;
	T2_ = sin(ang);
	result.y = ((NF)(p.y) + (NF)(((NF)(T2_) * (NF)(dist))));
	popFrame();
	return result;
}

N_NIMCALL(void, rotate_TmBpU7PM0PUMdVzew9ao9cBg)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF rad) {
	NF c;
	NF s;
	NF newx;
	nimfr_("rotate", "basic2d.nim");
	nimln_(759, "basic2d.nim");
	c = cos(rad);
	nimln_(760, "basic2d.nim");
	s = sin(rad);
	nimln_(761, "basic2d.nim");
	newx = ((NF)(((NF)((*p).x) * (NF)(c))) - (NF)(((NF)((*p).y) * (NF)(s))));
	nimln_(762, "basic2d.nim");
	(*p).y = ((NF)(((NF)((*p).y) * (NF)(c))) + (NF)(((NF)((*p).x) * (NF)(s))));
	nimln_(763, "basic2d.nim");
	(*p).x = newx;
	popFrame();
}

N_NIMCALL(void, rotate_RPykYWgbcjdNOc9bHPQTgZQ)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF rad, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org) {
	NF c;
	NF s;
	NF newx;
	nimfr_("rotate", "basic2d.nim");
	nimln_(769, "basic2d.nim");
	c = cos(rad);
	nimln_(770, "basic2d.nim");
	s = sin(rad);
	nimln_(771, "basic2d.nim");
	newx = ((NF)(((NF)(((NF)(((NF)((*p).x) - (NF)(org.x))) * (NF)(c))) - (NF)(((NF)(((NF)((*p).y) - (NF)(org.y))) * (NF)(s))))) + (NF)(org.x));
	nimln_(772, "basic2d.nim");
	(*p).y = ((NF)(((NF)(((NF)(((NF)((*p).y) - (NF)(org.y))) * (NF)(c))) + (NF)(((NF)(((NF)((*p).x) - (NF)(org.x))) * (NF)(s))))) + (NF)(org.y));
	nimln_(773, "basic2d.nim");
	(*p).x = newx;
	popFrame();
}

static N_INLINE(void, scale_PA4uX2ATo70xFXHtdtKw0wbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF fac) {
	nimfr_("scale", "basic2d.nim");
	nimln_(777, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*p).x), fac);
	nimln_(778, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*p).y), fac);
	popFrame();
}

static N_INLINE(void, scale_rlg9cR5LaB6M0z6QOTP0e6wbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF fac, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org) {
	nimfr_("scale", "basic2d.nim");
	nimln_(782, "basic2d.nim");
	(*p).x = ((NF)(((NF)(((NF)((*p).x) - (NF)(org.x))) * (NF)(fac))) + (NF)(org.x));
	nimln_(783, "basic2d.nim");
	(*p).y = ((NF)(((NF)(((NF)((*p).y) - (NF)(org.y))) * (NF)(fac))) + (NF)(org.y));
	popFrame();
}

static N_INLINE(void, stretch_TBlDxsuzdpvxCd0fecb21Abasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF facx, NF facy) {
	nimfr_("stretch", "basic2d.nim");
	nimln_(788, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*p).x), facx);
	nimln_(789, "basic2d.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*p).y), facy);
	popFrame();
}

static N_INLINE(void, stretch_vwKutqxWzKGeCuLFZUw9a7wbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF facx, NF facy, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug org) {
	nimfr_("stretch", "basic2d.nim");
	nimln_(794, "basic2d.nim");
	(*p).x = ((NF)(((NF)(((NF)((*p).x) - (NF)(org.x))) * (NF)(facx))) + (NF)(org.x));
	nimln_(795, "basic2d.nim");
	(*p).y = ((NF)(((NF)(((NF)((*p).y) - (NF)(org.y))) * (NF)(facy))) + (NF)(org.y));
	popFrame();
}

static N_INLINE(void, move_DwI9cSc9ce7A3ZXsjGyqZjWQbasic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, NF dx, NF dy) {
	nimfr_("move", "basic2d.nim");
	nimln_(799, "basic2d.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*p).x), dx);
	nimln_(800, "basic2d.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*p).y), dy);
	popFrame();
}

static N_INLINE(void, move_FhMmgV9c9csOjbyaRVR6fA3w_3basic2d)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* p, tyObject_Vector2d_KzVBdX0o9c9aJpcyeuR3YopA v) {
	nimfr_("move", "basic2d.nim");
	nimln_(804, "basic2d.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*p).x), v.x);
	nimln_(805, "basic2d.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*p).y), v.y);
	popFrame();
}

N_NIMCALL(NF, sgnArea_kFyWnP1SkVxW8qpnjM9aWKA)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug c) {
	NF result;
	nimfr_("sgnArea", "basic2d.nim");
{	result = (NF)0;
	nimln_(812, "basic2d.nim");
	result = ((NF)(((NF)(((NF)(((NF)(b.x) - (NF)(c.x))) * (NF)(((NF)(b.y) - (NF)(a.y))))) - (NF)(((NF)(((NF)(b.y) - (NF)(c.y))) * (NF)(((NF)(b.x) - (NF)(a.x))))))) * (NF)(5.0000000000000000e-001));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NF, area_kFyWnP1SkVxW8qpnjM9aWKA_2)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug a, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug b, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug c) {
	NF result;
	NF T1_;
	nimfr_("area", "basic2d.nim");
{	result = (NF)0;
	nimln_(816, "basic2d.nim");
	T1_ = (NF)0;
	T1_ = sgnArea_kFyWnP1SkVxW8qpnjM9aWKA(a, b, c);
	result = (T1_ < 0? -(T1_) : (T1_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug, closestPoint_JIOsw8Im7T8GxzdK9ame5bA)(tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug p, tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug* pts, NI ptsLen_0) {
	tyObject_Point2d_eVNY8xahmVtt29cZz5fuKug result;
	NI bestidx;
	NF bestdist;
	NF curdist;
	nimfr_("closestPoint", "basic2d.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(821, "basic2d.nim");
	{
		if (!!((((NI) 0) < ptsLen_0))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_uZDJJp1iqREI0Whfe9c2S0w_6));
	}
	LA3_: ;
	nimln_(824, "basic2d.nim");
	bestidx = ((NI) 0);
	nimln_(825, "basic2d.nim");
	if ((NU)(((NI) 0)) >= (NU)(ptsLen_0)) raiseIndexError();
	bestdist = sqrDist_inohp9bGa7FVYBb9biOHHX4g(p, pts[((NI) 0)]);
	curdist = (NF)0;
	{
		NI idx;
		NI colontmp_;
		NI res;
		idx = (NI)0;
		colontmp_ = (NI)0;
		nimln_(828, "basic2d.nim");
		colontmp_ = (ptsLen_0-1);
		nimln_(1986, "system.nim");
		res = ((NI) 1);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_uZDJJp1iqREI0Whfe9c2S0w_7;
				if (!(res <= colontmp_)) goto LA7;
				nimln_(1988, "system.nim");
				idx = res;
				nimln_(829, "basic2d.nim");
				if ((NU)(idx) >= (NU)(ptsLen_0)) raiseIndexError();
				curdist = sqrDist_inohp9bGa7FVYBb9biOHHX4g(p, pts[idx]);
				nimln_(830, "basic2d.nim");
				{
					if (!(curdist < bestdist)) goto LA10_;
					nimln_(831, "basic2d.nim");
					bestidx = idx;
					nimln_(832, "basic2d.nim");
					bestdist = curdist;
				}
				LA10_: ;
				nimln_(1989, "system.nim");
				TM_uZDJJp1iqREI0Whfe9c2S0w_7 = addInt(res, ((NI) 1));
				res = (NI)(TM_uZDJJp1iqREI0Whfe9c2S0w_7);
			} LA7: ;
		}
	}
	nimln_(834, "basic2d.nim");
	if ((NU)(bestidx) >= (NU)(ptsLen_0)) raiseIndexError();
	result = pts[bestidx];
	popFrame();
	return result;
}

N_NIMCALL(NF, normAngle_P8e2c9aikm3VRG6gsXpFpIA)(NF ang) {
	NF result;
	nimfr_("normAngle", "basic2d.nim");
{	result = (NF)0;
	nimln_(844, "basic2d.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (0.0 <= ang);
		if (!(T3_)) goto LA4_;
		T3_ = (ang < 6.2831853071795862e+000);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(845, "basic2d.nim");
		result = ang;
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(847, "basic2d.nim");
	result = mod_sGqENdekUaHyJla6nH3ncQ(ang, 6.2831853071795862e+000);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NF, degToRad_6PAXAFwfQC69aYEj2QnQRxwbasic2d)(NF deg) {
	NF result;
	nimfr_("degToRad", "basic2d.nim");
	result = (NF)0;
	nimln_(850, "basic2d.nim");
	nimln_(851, "basic2d.nim");
	result = ((NF)(deg) / (NF)(5.7295779513082323e+001));
	popFrame();
	return result;
}

static N_INLINE(NF, radToDeg_XBsJzgPXkAYChZQhqMAzsgbasic2d)(NF rad) {
	NF result;
	nimfr_("radToDeg", "basic2d.nim");
	result = (NF)0;
	nimln_(854, "basic2d.nim");
	nimln_(855, "basic2d.nim");
	result = ((NF)(rad) * (NF)(5.7295779513082323e+001));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dInit000)(void) {
	nimfr_("basic2d", "basic2d.nim");
	nimln_(95, "basic2d.nim");
	IDMATRIX_DQf5P8YCykuDxNmZ5bvG7g = matrix2d_ZkrhJTvT5qdZLXWIJxuuVw(1.0000000000000000e+000, 0.0, 0.0, 1.0000000000000000e+000, 0.0, 0.0);
	nimln_(97, "basic2d.nim");
	ORIGO_fcPFYT9cYuzJZVhuTlBCWIA = point2d_4HtTb6DBuFYILwb7lqld9agbasic2d(0.0, 0.0);
	nimln_(99, "basic2d.nim");
	XAXIS_cHisHYvnFnWkQFsXQwR8LA = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(1.0000000000000000e+000, 0.0);
	nimln_(101, "basic2d.nim");
	YAXIS_Tg25xvoRc1btSr7LczyLoQ = vector2d_lQ8UcHP21qhMsKlLR1WveQbasic2d(0.0, 1.0000000000000000e+000);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_basic2dDatInit000)(void) {
}

